package p000;

/* renamed from: abzh */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
enum abzh {
    OK,
    NO_UNIVERSAL_SECTION_MAPPING,
    FILTERED_BY_SPEC,
    NOT_OMNIBOX_CORPUS_IN_CHROME_OMNIBOX,
    NOT_AUTHORIZED_FOR_INTERNAL_CORPUS,
    PACKAGE_NOT_GLOBALLY_SEARCHABLE,
    CONTENT_CORPUS_NOT_ENABLED,
    CLIENT_NOT_EXIST,
    SETTINGS_USER_DISABLED
}
