package p000;

import com.felicanetworks.mfc.mfi.BaseMfiEventCallback;
import com.felicanetworks.sdu.ErrorInfo;

/* renamed from: baup */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum baup {
    UNSPECIFIED(0),
    SUCCESS(1),
    UNKNOWN_ERROR(2),
    ANDROID_DOWNLOADER_UNKNOWN(100),
    ANDROID_DOWNLOADER_CANCELED(101),
    ANDROID_DOWNLOADER_INVALID_REQUEST(102),
    ANDROID_DOWNLOADER_HTTP_ERROR(ErrorInfo.TYPE_SDU_COMMUNICATIONERROR),
    ANDROID_DOWNLOADER_REQUEST_ERROR(ErrorInfo.TYPE_SDU_FAILED),
    ANDROID_DOWNLOADER_RESPONSE_OPEN_ERROR(ErrorInfo.TYPE_SDU_MEMORY_FULL),
    ANDROID_DOWNLOADER_RESPONSE_CLOSE_ERROR(106),
    ANDROID_DOWNLOADER_NETWORK_IO_ERROR(107),
    ANDROID_DOWNLOADER_DISK_IO_ERROR(108),
    ANDROID_DOWNLOADER_FILE_SYSTEM_ERROR(109),
    ANDROID_DOWNLOADER_UNKNOWN_IO_ERROR(110),
    ANDROID_DOWNLOADER_OAUTH_ERROR(111),
    ANDROID_DOWNLOADER2_ERROR(BaseMfiEventCallback.TYPE_UNKNOWN_ERROR),
    GROUP_NOT_FOUND_ERROR(300),
    DOWNLOAD_MONITOR_NOT_PROVIDED_ERROR(ErrorInfo.TYPE_FSC_HTTP_ERROR),
    INSECURE_URL_ERROR(302),
    LOW_DISK_ERROR(303),
    UNABLE_TO_CREATE_FILE_URI_ERROR(304),
    SHARED_FILE_NOT_FOUND_ERROR(305),
    MALFORMED_FILE_URI_ERROR(306),
    UNABLE_TO_CREATE_MOBSTORE_RESPONSE_WRITER_ERROR(307),
    UNABLE_TO_VALIDATE_DOWNLOAD_FILE_ERROR(308),
    DOWNLOADED_FILE_NOT_FOUND_ERROR(309),
    DOWNLOADED_FILE_CHECKSUM_MISMATCH_ERROR(310),
    UNABLE_TO_SERIALIZE_DOWNLOAD_TRANSFORM_ERROR(311),
    DOWNLOAD_TRANSFORM_IO_ERROR(312),
    FINAL_FILE_CHECKSUM_MISMATCH_ERROR(313),
    DELTA_DOWNLOAD_BASE_FILE_NOT_FOUND_ERROR(314),
    DELTA_DOWNLOAD_DECODE_IO_ERROR(315),
    UNABLE_TO_UPDATE_FILE_STATE_ERROR(316),
    UNABLE_TO_UPDATE_GROUP_METADATA_ERROR(317);
    

    /* renamed from: I */
    public final int f101829I;

    private baup(int i) {
        this.f101829I = i;
    }
}
