package p000;

/* renamed from: bebf */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum bebf {
    RESTORE_REQUESTED,
    RESTORE_INITIATED,
    RESTORE_IN_PROGRESS,
    RESTORE_PAUSED_NO_WIFI,
    RESTORE_COMPLETE_CANCELLED,
    RESTORE_COMPLETE_SUCCESS,
    RESTORE_COMPLETE_FAILED,
    RESTORE_ERROR_DENIED_PERMISSION,
    RESTORE_ERROR_UNKNOWN,
    RESTORE_ERROR_RETRY
}
