package p000;

import com.felicanetworks.mfc.FelicaException;
import com.felicanetworks.mfc.KeyInformation;
import com.google.autofill.detection.p098ml.AndroidInputTypeSignal;

/* renamed from: bpue */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public final class bpue {
    /* renamed from: a */
    public static int m112288a(int i) {
        switch (i) {
            case 0:
                return 1;
            case 1:
                return 2;
            case 2:
            case 7:
            case 8:
            case 9:
            case 12:
            case 19:
            case 22:
            case 23:
            case 24:
            case 25:
            case 26:
            case 27:
            case 29:
            case 35:
            case 36:
            case FelicaException.TYPE_ILLEGAL_METHOD_CALL:
            case 41:
            case 72:
            default:
                return 0;
            case 3:
                return 4;
            case 4:
                return 5;
            case 5:
                return 6;
            case 6:
                return 7;
            case 10:
                return 11;
            case 11:
                return 12;
            case 13:
                return 14;
            case 14:
                return 15;
            case 15:
                return 16;
            case 16:
                return 17;
            case 17:
                return 18;
            case 18:
                return 19;
            case 20:
                return 21;
            case 21:
                return 22;
            case 28:
                return 29;
            case 30:
                return 31;
            case 31:
                return 32;
            case 32:
                return 33;
            case 33:
                return 34;
            case 34:
                return 35;
            case FelicaException.TYPE_NOT_CLOSED:
                return 38;
            case FelicaException.TYPE_USED_BY_OTHER_APP:
                return 40;
            case FelicaException.TYPE_PUSH_FAILED:
                return 41;
            case FelicaException.TYPE_ALREADY_ACTIVATED:
                return 43;
            case FelicaException.TYPE_GET_BLOCK_COUNT_INFORMATION_FAILED:
                return 44;
            case FelicaException.TYPE_RESET_FAILED:
                return 45;
            case FelicaException.TYPE_GET_SYSTEM_CODE_LIST_FAILED:
                return 46;
            case FelicaException.TYPE_GET_CONTAINER_ID_FAILED:
                return 47;
            case 47:
                return 48;
            case 48:
                return 49;
            case FelicaException.TYPE_CURRENTLY_ACTIVATING:
                return 50;
            case 50:
                return 51;
            case 51:
                return 52;
            case 52:
                return 53;
            case 53:
                return 54;
            case 54:
                return 55;
            case 55:
                return 56;
            case FelicaException.TYPE_ACTIVATE_FAILED:
                return 57;
            case 57:
                return 58;
            case FelicaException.TYPE_OFFLINE_CANCELED:
                return 59;
            case FelicaException.TYPE_NOW_EXECUTING_FALP:
                return 60;
            case FelicaException.TYPE_MFC_NOT_FOUND:
                return 61;
            case FelicaException.TYPE_INITIATE_ADHOC_ERROR:
                return 62;
            case 62:
                return 63;
            case 63:
                return 64;
            case 64:
                return 65;
            case KeyInformation.AES128_DES56:
                return 66;
            case 66:
                return 67;
            case KeyInformation.AES128_DES112:
                return 68;
            case 68:
                return 69;
            case 69:
                return 70;
            case 70:
                return 71;
            case 71:
                return 72;
            case 73:
                return 74;
            case 74:
                return 75;
            case 75:
                return 76;
            case 76:
                return 77;
            case 77:
                return 78;
            case 78:
                return 79;
            case KeyInformation.AES128:
                return 80;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_LONG_MESSAGE /*80*/:
                return 81;
            case 81:
                return 82;
            case 82:
                return 83;
        }
    }
}
