package p000;

import com.felicanetworks.mfc.FelicaException;
import com.felicanetworks.mfc.KeyInformation;
import com.felicanetworks.mfc.mfi.BaseMfiEventCallback;
import com.felicanetworks.mfc.mfi.MfiClientException;
import com.felicanetworks.sdu.ErrorInfo;
import com.google.android.gms.org.conscrypt.PSKKeyManager;
import com.google.autofill.detection.p098ml.AndroidInputTypeSignal;

/* renamed from: bsmx */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum bsmx implements bxvp {
    CONTEXT_ID_UNSPECIFIED(0),
    ACTIVITY_CONTROLS_WEB(365),
    ACTIVITY_CONTROLS_WEBVIEW(366),
    ADH_CONSENT_WEB(379),
    ADS_SETTINGS_CONSENT_BUMP_1_WEB(344),
    ADS_SETTINGS_CONSENT_BUMP_1_WEBVIEW(415),
    ADS_SETTINGS_WEB(345),
    ADS_SETTINGS_WEBVIEW(414),
    ANDROID_AUTO_SETUP_WIZARD_GOOGLE_SERVICES(259),
    ANDROID_AUTO_SETUP_WIZARD_GOOGLE_SERVICES_ADD_ACCOUNT(260),
    ANDROID_BACKUP_DRIVE_BACKUP_SETTINGS(16),
    ANDROID_BACKUP_OPTIN(15),
    ANDROID_BACKUP_SET_BACKUP_ACCOUNT(14),
    ANDROID_BACKUP_SET_BACKUP_ACCOUNT_FLOW(17),
    ANDROID_LOCATION_SERVICES_CONSENT_UI(46),
    ANDROID_SETUP_WIZARD_GOOGLE_SERVICES(8),
    ANDROID_SETUP_WIZARD_GOOGLE_SERVICES_ADD_ACCOUNT(18),
    ANDROID_SETUP_WIZARD_PIXEL_TOS_DEFERRED_SETUP(124),
    ANDROID_SETUP_WIZARD_PIXEL_TOS_INITIAL_SETUP(125),
    ANDROID_TV_SETUP_WIZARD_FLOW(32),
    ANDROID_WIFI_SCAN_SETTINGS_UPDATE_PRE_P_CONSENT(129),
    APPLIED_CS_WITH_ANDROID_WEB_USER_REGISTRATION(161),
    ASTERISM_ANDROID_FUNCTION_INVOKED(353),
    ASTERISM_ANDROID_SETUP_INVOKED(351),
    ASTERISM_ANDROID_USER_INVOKED(352),
    BQ_DTS_WEB_CREATE_CONFIG(296),
    BQ_DTS_WEB_EDIT_CONFIG(297),
    CHROME_OS_ARC_REMOVE_ALL_ANDROID_APPS_DIALOG(242),
    CHROME_OS_ARC_SETUP_DIALOG(202),
    CHROME_SYNC_SETUP_CONSENT_DIALOG(66),
    CHROME_UNIFIED_CONSENT_DIALOG(252),
    CLOUD_AGREEMENT_CONTEXT(355),
    CLOUD_CONSOLE_WEB_PERSONALIZATION_SETTINGS(127),
    CLOUD_TALENT_SOLUTION_DATA_WEB_LOGGING_SETTINGS(243),
    COLABORATORY_PROPAGATE_DRIVE_CREDS_CONSENT_UI(431),
    COLABORATORY_SUBSCRIPTION_BUY_FLOW_UI(465),
    CONSENT_CAMPAIGN_CONSENT_BUMP_1(222),
    CONSENT_CAMPAIGN_CONSENT_BUMP_2(223),
    CONSENT_CAMPAIGN_WEB_DASHER_TO_CONSUMER_CONVERSION_UI(456),
    CONSTELLATION_CONSENT_GMSCORE_SETTINGS_UI(5),
    CONSTELLATION_CONSENT_MINUTEMAID_SETUP_WIZARD(4),
    CONTACTS_SYNC_ANDROID_BACKUP_SYNC_OPT_IN(426),
    CONTACTS_SYNC_ANDROID_CONTACTS_APP_PROMO(441),
    CROWDSOURCE_ANDROID_GAZELLE_CONSENT_SCREEN(398),
    CROWDSOURCE_ANDROID_IMAGE_CAPTURE_CONSENT_SCREEN(189),
    CROWDSOURCE_ANDROID_IMAGE_CAPTURE_OPENSOURCE_DIALOG(190),
    CROWDSOURCE_ANDROID_MOBILE_RAID_CONSENT_SCREEN(432),
    CROWDSOURCE_ANDROID_SETTINGS_UI(188),
    CROWDSOURCE_ANDROID_SMART_CAMERA_OPENSOURCE_DIALOG(491),
    CROWDSOURCE_LEADERBOARDS_CONSENT_SCREEN(466),
    CROWDSOURCE_SETTINGS_UI(467),
    CRUISER_ANDROID_CONSENT_UI(346),
    CRUISER_WEB_PUBMATE_TOS_UI(430),
    CRUISER_WEB_REDEMPTION_CONSENT_UI(501),
    DOMAIN_REGISTRAR_RESELLER_API_WHOIS_CONSENT_FLOW(388),
    DOMAIN_REGISTRAR_WEB_MANAGE_DOMAINS_WHOIS_CONSENT_FLOW(177),
    DOMAIN_REGISTRAR_WEB_REGISTRATION_WHOIS_CONSENT_FLOW(178),
    DRIVE_ANDROID_SETTINGS(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PHONETIC),
    DRIVE_IOS_SETTINGS_BACKUP_FLOW(113),
    DRIVE_WEB_SETTINGS(312),
    DUO_ANDROID_DOWNGRADE_FROM_SETTINGS(321),
    DUO_ANDROID_EXISTING_USER_BUMP_FROM_NOTIFICATION(225),
    DUO_ANDROID_EXISTING_USER_BUMP_FROM_SETTINGS(226),
    DUO_ANDROID_NEW_USER_SETUP_FLOW(227),
    DUO_ANDROID_REWARDS_ONBOARDING_FLOW(246),
    DUO_IOS_DOWNGRADE_FROM_SETTINGS(322),
    DUO_IOS_EXISTING_USER_BUMP_FROM_NOTIFICATION(228),
    DUO_IOS_EXISTING_USER_BUMP_FROM_SETTINGS(229),
    DUO_IOS_NEW_USER_SETUP_FLOW(230),
    DUO_IOS_REWARDS_ONBOARDING_FLOW(247),
    DUO_WEB_NEW_USER_SETUP_FLOW(324),
    FAMILIES_ANDROID_FAMILYLINK_ONBOARDING_V1(173),
    FAMILIES_ANDROID_FAMILYLINK_ONBOARDING_V2(174),
    FAMILIES_ANDROID_FAMILY_CREATION(44),
    FAMILIES_IOS_FAMILYLINK_ONBOARDING_V1(175),
    FAMILIES_IOS_FAMILYLINK_ONBOARDING_V2(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_FILTER),
    FAMILYLINK_ANDROID_DEVICE_SETTINGS_UI(164),
    FAMILYLINK_ANDROID_KIDS_MODULE_SUPERVISION_OPTIN_UI(255),
    FAMILYLINK_ANDROID_KIDS_MODULE_SUPERVISION_OPTOUT_UI(PSKKeyManager.MAX_KEY_LENGTH_BYTES),
    FAMILYLINK_ANDROID_LOCATION_CONSENT_UI(184),
    FAMILYLINK_ANDROID_SUPERVISION_OPTOUT_UI(257),
    FAMILYLINK_CHROME_OS_SUPERVISION_OPTIN_UI(419),
    FAMILYLINK_IOS_DEVICE_SETTINGS_UI(165),
    FAMILYLINK_IOS_LOCATION_CONSENT_UI(185),
    FAMILYLINK_IOS_SUPERVISION_OPTOUT_UI(258),
    FAMILYLINK_WEB_DEVICE_SETTINGS_UI(166),
    FAMILYLINK_WEB_PARENTAL_CONSENT_CC_UI(497),
    FAMILYLINK_WEB_PARENTAL_CONSENT_RAPT_UI(498),
    FAMILYLINK_WEB_SUPERVISION_OPTIN_UI(284),
    FITNESS_ANDROID_HISTORY_UI(348),
    FITNESS_ANDROID_HOME_UI(349),
    FITNESS_ANDROID_ONBOARDING_FLOW(237),
    FITNESS_ANDROID_SETTINGS_UI(238),
    FITNESS_ANDROID_WEAR_HOME_UI(358),
    FITNESS_ANDROID_WEAR_ONBOARDING_FLOW(418),
    FITNESS_ANDROID_WEAR_SETTINGS_UI(359),
    FITNESS_IOS_ONBOARDING_FLOW(305),
    FITNESS_IOS_SETTINGS_UI(306),
    FLOURISH_ANDROID_CONTRIBUTE_FLOW(428),
    FLOURISH_ANDROID_REVOKE_CONSENT_PROMPT(429),
    FREIGHTER_ANDROID_LANDING_SCREEN_POP_UP(186),
    FREIGHTER_ANDROID_SETTINGS(187),
    GAIA_WEB_SIGNUP(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_WEB_PASSWORD),
    GBOARD_ANDROID_DONATE_VOICE_CONSENT(505),
    GBOARD_ANDROID_DONATE_VOICE_OPT_OUT(506),
    GBOARD_ANDROID_TYPING_HISTORY_SYNC(286),
    GCP_MARKETPLACE_DEPLOYMENT_CONFIG(307),
    GCP_MARKETPLACE_PRODUCT_PURCHASE(354),
    GCP_MARKETPLACE_WEB_SOLUTION_TRIAL(509),
    GOOGLE_ACCOUNT_WEB_PRIVACY_CHECKUP(250),
    GOOGLE_ACCOUNT_WEB_WHITEPAGES_UI(251),
    GOOGLE_ASSISTANT_ACTION_LINK_CONFIRMATION(316),
    GOOGLE_ASSISTANT_ANDROID_CONFIRM_REJECT(43),
    GOOGLE_ASSISTANT_ANDROID_CONSENT_UI(42),
    GOOGLE_ASSISTANT_ANDROID_DUO_ACCOUNT_LEVEL_SETTINGS(233),
    GOOGLE_ASSISTANT_ANDROID_DUO_DEVICE_LEVEL_SETTINGS(234),
    GOOGLE_ASSISTANT_ANDROID_FACE_MATCH_ENROLLMENT_CONSENT(380),
    GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_ONBOARDING_STANDALONE(149),
    GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_ONBOARDING_WITH_VOICE_MATCH(MfiClientException.TYPE_MFICLIENT_REMOTE_ACCESS_FAILED),
    GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_SETTINGS(MfiClientException.TYPE_MFICLIENT_NOT_FOUND),
    GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_WITH_FACE_MATCH(381),
    GOOGLE_ASSISTANT_ANDROID_UNICORN_FACE_MATCH_ENROLLMENT_CONSENT(382),
    GOOGLE_ASSISTANT_ANDROID_UNICORN_PERSONAL_RESULTS_WITH_FACE_MATCH(383),
    GOOGLE_ASSISTANT_ANDROID_VOICE_MATCH_ONBOARDING_GOOGLE_HOME(MfiClientException.TYPE_MFICLIENT_NOT_ACTIVATED),
    GOOGLE_ASSISTANT_ANDROID_VOICE_MATCH_ONBOARDING_OPA_ANDROID(MfiClientException.TYPE_MFICLIENT_STARTED),
    GOOGLE_ASSISTANT_ANDROID_VOICE_MATCH_SETTINGS(MfiClientException.TYPE_MFICLIENT_NOT_STARTED),
    GOOGLE_ASSISTANT_CROS_CONSENT_UI(287),
    GOOGLE_ASSISTANT_IOS_CONFIRM_REJECT(59),
    GOOGLE_ASSISTANT_IOS_CONSENT_UI(58),
    GOOGLE_ASSISTANT_IOS_DUO_ACCOUNT_LEVEL_SETTINGS(235),
    GOOGLE_ASSISTANT_IOS_DUO_DEVICE_LEVEL_SETTINGS(236),
    GOOGLE_ASSISTANT_IOS_FACE_MATCH_ENROLLMENT_CONSENT(384),
    GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_ONBOARDING_STANDALONE(MfiClientException.TYPE_ILLEGAL_LINKAGE_DATA),
    GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_ONBOARDING_WITH_VOICE_MATCH(MfiClientException.TYPE_NO_ACCOUNT_INFO),
    GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_SETTINGS(MfiClientException.TYPE_CARD_NOT_CACHED),
    GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_WITH_FACE_MATCH(385),
    GOOGLE_ASSISTANT_IOS_UNICORN_FACE_MATCH_ENROLLMENT_CONSENT(386),
    GOOGLE_ASSISTANT_IOS_UNICORN_PERSONAL_RESULTS_WITH_FACE_MATCH(387),
    GOOGLE_ASSISTANT_IOS_VOICE_MATCH_ONBOARDING_GOOGLE_HOME(MfiClientException.TYPE_ILLEGAL_CARD_OPERATION),
    GOOGLE_ASSISTANT_IOS_VOICE_MATCH_ONBOARDING_OPA_IOS(MfiClientException.TYPE_MFICLIENT_CURRENTLY_ONLINE),
    GOOGLE_ASSISTANT_IOS_VOICE_MATCH_SETTINGS(160),
    GOOGLE_ASSISTANT_KAIOS_CONSENT_UI(327),
    GOOGLE_HOME_ANDROID_ASSISTANT_SETTINGS(97),
    GOOGLE_HOME_ANDROID_BROWSE_CONTENT_DETAILS_VIEW(167),
    GOOGLE_HOME_ANDROID_BROWSE_SHELVES_VIEW(168),
    GOOGLE_HOME_ANDROID_CONNECTED_ACCOUNTS_SETTINGS(169),
    GOOGLE_HOME_ANDROID_DEVICE_SETTINGS(98),
    GOOGLE_HOME_ANDROID_E911_OOBE(470),
    GOOGLE_HOME_ANDROID_E911_SETTINGS(471),
    GOOGLE_HOME_ANDROID_EMAIL_NOTIFICATIONS_SETTINGS(99),
    GOOGLE_HOME_ANDROID_FAMILIAR_FACE_DETECTION_OOBE(472),
    GOOGLE_HOME_ANDROID_FAMILIAR_FACE_DETECTION_SETTINGS(473),
    GOOGLE_HOME_ANDROID_FIRST_RUN(100),
    GOOGLE_HOME_ANDROID_HOME_TAB_ACTION_CHIPS(483),
    GOOGLE_HOME_ANDROID_INVITEE_INITIATED_INVITE(261),
    GOOGLE_HOME_ANDROID_MANAGER_INITIATED_INVITE(262),
    GOOGLE_HOME_ANDROID_MIGRATION_FLOW(434),
    GOOGLE_HOME_ANDROID_NEST_AWARE_TRIAL_OFFER(493),
    GOOGLE_HOME_ANDROID_NEST_LINKING_FLOW(ErrorInfo.TYPE_FSC_OTHER_ERROR),
    GOOGLE_HOME_ANDROID_NEW_MANAGER_OOBE_FLOW(253),
    GOOGLE_HOME_ANDROID_NEW_MANAGER_OOBE_FLOW_NEST(373),
    GOOGLE_HOME_ANDROID_OOBE_FLOW(101),
    GOOGLE_HOME_ANDROID_SOUND_SENSING_OOBE(474),
    GOOGLE_HOME_ANDROID_SOUND_SENSING_SETTINGS(475),
    GOOGLE_HOME_IOS_APP_CRASH_UPLOAD_CONSENT_DIALOG(163),
    GOOGLE_HOME_IOS_ASSISTANT_SETTINGS(102),
    GOOGLE_HOME_IOS_BROWSE_SHELVES_VIEW(170),
    GOOGLE_HOME_IOS_CONNECTED_ACCOUNTS_SETTINGS(171),
    GOOGLE_HOME_IOS_DEVICE_OR_ACCOUNT_LEVEL_SETTINGS_SEE_BUG_116807852(ErrorInfo.TYPE_SDU_COMMUNICATIONERROR),
    GOOGLE_HOME_IOS_DEVICE_SETTINGS(294),
    GOOGLE_HOME_IOS_E911_OOBE(476),
    GOOGLE_HOME_IOS_E911_SETTINGS(477),
    GOOGLE_HOME_IOS_EMAIL_NOTIFICATIONS_SETTINGS(ErrorInfo.TYPE_SDU_FAILED),
    GOOGLE_HOME_IOS_FAMILIAR_FACE_DETECTION_OOBE(478),
    GOOGLE_HOME_IOS_FAMILIAR_FACE_DETECTION_SETTINGS(479),
    GOOGLE_HOME_IOS_FIRST_RUN(ErrorInfo.TYPE_SDU_MEMORY_FULL),
    GOOGLE_HOME_IOS_HOME_TAB_VIEW(484),
    GOOGLE_HOME_IOS_INVITEE_INITIATED_INVITE(263),
    GOOGLE_HOME_IOS_MANAGER_INITIATED_INVITE(264),
    GOOGLE_HOME_IOS_MIGRATION_FLOW(435),
    GOOGLE_HOME_IOS_NEST_AWARE_TRIAL_OFFER(494),
    GOOGLE_HOME_IOS_NEST_LINKING_FLOW(400),
    GOOGLE_HOME_IOS_NEW_MANAGER_OOBE_FLOW(254),
    GOOGLE_HOME_IOS_NEW_MANAGER_OOBE_FLOW_NEST(374),
    GOOGLE_HOME_IOS_OOBE_FLOW(106),
    GOOGLE_HOME_IOS_SOUND_SENSING_OOBE(480),
    GOOGLE_HOME_IOS_SOUND_SENSING_SETTINGS(481),
    GOOGLE_HOME_WEB_FRONTEND_NEW_MANAGER_OOBE_FLOW_NEST(375),
    GOOGLE_HOME_WEB_FRONTEND_PROMOTION(450),
    GOOGLE_JACQUARD_ANDROID_ASSIGN_ABILITY_FLOW(367),
    GOOGLE_JACQUARD_ANDROID_ONBOARDING_FLOW(368),
    GOOGLE_JACQUARD_ANDROID_SETTING_FLOW(369),
    GOOGLE_JACQUARD_IOS_ASSIGN_ABILITY_FLOW(370),
    GOOGLE_JACQUARD_IOS_ONBOARDING_FLOW(371),
    GOOGLE_JACQUARD_IOS_SETTING_FLOW(372),
    GOOGLE_MAPS_AUTOMOTIVE_ANDROID_NAV_SESSION_LOGGING_PERMISSION(485),
    GOOGLE_MAPS_AUTOMOTIVE_ANDROID_OFFLINE_MAPS_DOWNLOAD_PERMISSION(486),
    GOOGLE_MAPS_AUTOMOTIVE_ANDROID_PRIVACY_CENTER_HOME(487),
    GOOGLE_ONE_ANDROID_BACKUP_SETTINGS(361),
    GOOGLE_ONE_ANDROID_ENABLE_BACKUP_HOME_TAB(362),
    GOOGLE_ONE_ANDROID_FAMILY_SHARING_SETTING(268),
    GOOGLE_ONE_ANDROID_FAMILY_SHARING_SETTING_HOME_TAB(288),
    GOOGLE_ONE_ANDROID_MARKETING_SETTING(269),
    GOOGLE_ONE_ANDROID_PURCHASE_FLOW(270),
    GOOGLE_ONE_ANDROID_SETUP_BACKUP(363),
    GOOGLE_ONE_IOS_BACKUP_SETTINGS(458),
    GOOGLE_ONE_IOS_ENABLE_BACKUP_HOME_TAB(459),
    GOOGLE_ONE_IOS_FAMILY_SHARING_SETTING(460),
    GOOGLE_ONE_IOS_FAMILY_SHARING_SETTING_HOME_TAB(461),
    GOOGLE_ONE_IOS_MARKETING_SETTING(462),
    GOOGLE_ONE_IOS_PURCHASE_FLOW(463),
    GOOGLE_ONE_IOS_SETUP_BACKUP(464),
    GOOGLE_ONE_MARKETING_CONFIRMATION_EMAIL(271),
    GOOGLE_ONE_WEB_FAMILY_SHARING_SETTING(272),
    GOOGLE_ONE_WEB_FAMILY_SHARING_SETTING_LANDING_PAGE(285),
    GOOGLE_ONE_WEB_INITIAL_MARKETING_SETTING(273),
    GOOGLE_ONE_WEB_MARKETING_SETTING(274),
    GOOGLE_ONE_WEB_PURCHASE_FLOW(275),
    GOOGLE_ONE_WEB_SPONSORED_MEMBERSHIP_ONBOARDING_FLOW(357),
    GOOGLE_PAY_ANDROID_APP_SETTINGS(93),
    GOOGLE_PAY_ANDROID_IMPORT_GMAIL_CONSENT_UI(323),
    GOOGLE_PAY_ANDROID_LADDER_PROMOTION_CONSENT_UI(89),
    GOOGLE_PAY_ANDROID_LANDING_SCREEN(240),
    GOOGLE_PAY_ANDROID_LIVE_FEED_CARD(BaseMfiEventCallback.TYPE_AGREEMENT_NOT_ACCEPT),
    GOOGLE_PAY_ANDROID_PAYMENT_METHOD_DETAILS(239),
    GOOGLE_PAY_ANDROID_REFERRAL_INVITATION_UI(90),
    GOOGLE_PAY_ANDROID_REFERRAL_PROMO_CODE_APPLIED_UI(91),
    GOOGLE_PAY_ANDROID_REFERRAL_PROMO_CODE_ENTRY_UI(241),
    GOOGLE_PAY_ANDROID_VALUABLE_SIGNUP_UI(293),
    GOOGLE_PAY_GMSCORE_PAY_IMPORT_GMAIL_CONSENT_UI(425),
    GOOGLE_PAY_GMSCORE_PAY_SETTINGS(452),
    GOOGLE_PAY_GMSCORE_PAY_VALUABLE_SIGNUP_UI(489),
    GOOGLE_PAY_GMSCORE_TAPANDPAY_PROMOTION_NOTIFICATION(295),
    GOOGLE_PAY_GMSCORE_TAPANDPAY_SECOND_PARTY_TOKENIZATION_CONFIRMATION(20),
    GOOGLE_PAY_GMSCORE_TAPANDPAY_SETTINGS(19),
    GOOGLE_PAY_GMSCORE_TAPANDPAY_VISA_CHECKOUT_LINKING_UI(92),
    GOOGLE_PAY_IOS_APP_SETTINGS(231),
    GOOGLE_PAY_IOS_GMAIL_IMPORT_CONSENT_UI(448),
    GOOGLE_PAY_IOS_LIVE_FEED_CARD(232),
    GOOGLE_PAY_MOBILE_WEB_SETTINGS(457),
    GOOGLE_PAY_WEB_GAMMA_OPT_OUT_PAGE(266),
    GOOGLE_PAY_WEB_SETTINGS(267),
    GOOGLE_SHOPPING_TRANSACTION_ANDROID_ORDER_CREATION(300),
    GOOGLE_SHOPPING_TRANSACTION_IOS_ORDER_CREATION(ErrorInfo.TYPE_FSC_HTTP_ERROR),
    GOOGLE_SHOPPING_TRANSACTION_WEB_ORDER_CREATION(302),
    GOOGLE_WIFI_ANDROID_EMAIL_NOTIFICATIONS_SETTINGS(107),
    GOOGLE_WIFI_ANDROID_OOBE_FLOW(108),
    GOOGLE_WIFI_ANDROID_PRIVACY_SETTINGS(109),
    GOOGLE_WIFI_IOS_EMAIL_NOTIFICATIONS_SETTINGS(110),
    GOOGLE_WIFI_IOS_OOBE_FLOW(111),
    GOOGLE_WIFI_IOS_PRIVACY_SETTINGS(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_POSTAL_ADDRESS),
    HANCOCK_SIGN_UP(245),
    ITHACA_WEB_USER_OPT_OUT(303),
    ITHACA_WEB_USER_SIGN_UP(304),
    LOCATION_HISTORY_IOS_SETTINGS_UI(128),
    LOCATION_SHARING_ANDROID_TOS_SCREEN(21),
    LOCATION_SHARING_IOS_TOS_SCREEN(57),
    MADDEN_WEB_FINALIZE_BOOKING_FLOW(56),
    MADDEN_WEB_FINALIZE_PARKING_SESSION_FLOW(451),
    MADDEN_WEB_JOIN_WAITLIST_FLOW(ErrorInfo.TYPE_ACTIVATE_FELICA_UNKNOWN_ERROR),
    MINUTEMAID_ADD_PHONE_SPEED_BUMP(13),
    MINUTEMAID_LIGHTWEIGHT_SIGN_UP(424),
    MINUTEMAID_SIGN_IN_CONSENT_SPEED_BUMP(220),
    MINUTEMAID_SIGN_UP(7),
    MOBILE_CONSENT_FLOWS_ANDROID_GPAY_APP_NOTIFICATION_SETTINGS(378),
    MOBILE_CONSENT_FLOWS_ANDROID_LOHIBOSHE_DEMO(311),
    MOBILE_CONSENT_FLOWS_ANDROID_MAPS_HOME_SCREEN_CONTRIBUTE_TAB(449),
    MOBILE_CONSENT_FLOWS_ANDROID_MAPS_PERSONAL_SCORE_SETUP(453),
    MOBILE_CONSENT_FLOWS_ANDROID_MAPS_TIMELINE_ONBOARDING(445),
    MOBILE_CONSENT_FLOWS_ANDROID_MAPS_ULR_OOB_TUTORIAL(454),
    MOBILE_CONSENT_FLOWS_ANDROID_MAPS_YOUR_PLACES_VISITED(455),
    MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_CARD(416),
    MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_ON_APP_START(417),
    MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_ON_CONSENT_CHECK(438),
    MOBILE_CONSENT_FLOWS_ANDROID_PHOTOS_ASSISTANT_CARD(ErrorInfo.TYPE_FELICA_EXCEPTION_FELICA_NOT_AVAILABLE),
    MOBILE_CONSENT_FLOWS_ANDROID_PLAY_MUSIC_ON_APP_START(376),
    MOBILE_CONSENT_FLOWS_ANDROID_PLAY_MUSIC_ON_SETTINGS(377),
    MOBILE_CONSENT_FLOWS_ANDROID_SAFETYHUB_SHARING_ONBOARDING(403),
    MOBILE_CONSENT_FLOWS_ANDROID_YOUTUBE_MUSIC_HOME_LH_DIRECT_ASK(420),
    MOBILE_CONSENT_FLOWS_ANDROID_YOUTUBE_MUSIC_HOME_LH_PROMO(421),
    MOBILE_DATA_PLAN_ANDROID_CONSENT_CHANGE(328),
    NEST_ANDROID_NEST_AWARE_TRIAL_OFFER(495),
    NEST_AUTH_ANDROID_MERGE_FLOW(318),
    NEST_AUTH_IOS_MERGE_FLOW(319),
    NEST_AUTH_WEB_MERGE_FLOW(320),
    NEST_IOS_NEST_AWARE_TRIAL_OFFER(496),
    NEST_WEB_NEST_AWARE_TRIAL_OFFER(ErrorInfo.TYPE_FELICA_EXCEPTION_OTHER),
    NETAPP_CLOUD_VOLUMES_WEB_THIRD_PARTY_NOTICE_CONSENT(289),
    OFFLINE_RECEIPTS_ANDROID_MAPS_TIMELINE_OPT_IN_FLOW(221),
    PAISA_DONATION_MICROAPP_WEB(427),
    PAISA_MERCHANT_ANDROID_REGISTRATION_FLOW(313),
    PAISA_MICROAPPS_ANDROID_DISCLAIMER_REVOCATION_DIALOG(436),
    PAISA_MICROAPPS_ANDROID_PERMISSION_CONSENT_DIALOG(422),
    PAISA_MICROAPPS_FLUTTER_PERMISSION_CONSENT_DIALOG(443),
    PAISA_MICROAPPS_IOS_DISCLAIMER_REVOCATION_DIALOG(437),
    PAISA_MICROAPPS_IOS_PERMISSION_CONSENT_DIALOG(423),
    PAISA_MICROAPPS_PRIMER(ErrorInfo.TYPE_FELICA_EXCEPTION_TIMEOUT_OCCURRED),
    PAISA_MONEY_TAB_FLUTTER(500),
    PAISA_USER_MERCHANT_CREDIT_BOOK_CONSENT_FLOW_ANDROID(504),
    PAYMENTS_EMBEDDED_ADD_INSTRUMENT(114),
    PAYMENTS_EMBEDDED_BUY_FLOW(63),
    PAYMENTS_EMBEDDED_FIX_INSTRUMENT(115),
    PAYMENTS_EMBEDDED_IDENTITY_AND_CREDIT(116),
    PAYMENTS_EMBEDDED_INSTRUMENT_MANAGER(64),
    PAYMENTS_EMBEDDED_INTEGRATOR_API(117),
    PAYMENTS_EMBEDDED_ONLINE_CLICK_TO_ACCEPT(BaseMfiEventCallback.TYPE_SERVER_GENERAL_ERROR),
    PAYMENTS_EMBEDDED_SETTINGS(205),
    PAYMENTS_EMBEDDED_TAX_COLLECTION(BaseMfiEventCallback.TYPE_EXPIRED_MFI),
    PAYMENTS_EMBEDDED_UNAUTHORIZED_TRANSACTIONS(203),
    PAYMENTS_EMBEDDED_UPSTREAM(118),
    PAYMENTS_EMBEDDED_VERIFICATION(162),
    PERIODIC_PERSONALIZATION_REMINDERS_PRIVACY_CHECKUP(67),
    PHONE_TO_GAIA_ANDROID_NOTIFICATION(123),
    PHOTOS_ANDROID_AUTOBACKUP_CONVERSION_SHEET_FLOW(51),
    PHOTOS_ANDROID_AUTOBACKUP_ENABLE_BACKUP_SHEET_FLOW(52),
    PHOTOS_ANDROID_AUTOBACKUP_ONBOARDING_SHEET_FLOW(53),
    PHOTOS_ANDROID_AUTOBACKUP_SETTINGS_FLOW(54),
    PHOTOS_ANDROID_FACE_CLUSTERING_EXPLICIT_PERMISSION_FLOW(332),
    PHOTOS_ANDROID_FACE_CLUSTERING_ONBOARDING_DISCLAIMER_FLOW(333),
    PHOTOS_ANDROID_FACE_CLUSTERING_SETTINGS_FLOW(334),
    PHOTOS_ANDROID_FACE_CLUSTERING_STANDALONE_DISCLAIMER_FLOW(335),
    PHOTOS_ANDROID_GOOGLE_ONE_SWITCH_STORAGE_POLICY_FLOW(490),
    PHOTOS_ANDROID_GPLUS_DOWNLOAD_CONTENT(22),
    PHOTOS_ANDROID_SHARED_LIBRARY_PROPOSE_FLOW(23),
    PHOTOS_ANDROID_SHARED_LIBRARY_SETTINGS_FLOW(94),
    PHOTOS_ANDROID_SHARED_LIBRARY_WITHDRAWAL_FLOW(24),
    PHOTOS_IOS_AUTOBACKUP_ENABLE_BACKUP_FLOW(60),
    PHOTOS_IOS_AUTOBACKUP_ONBOARDING_FLOW(61),
    PHOTOS_IOS_AUTOBACKUP_SETTINGS_FLOW(62),
    PHOTOS_IOS_AUTOBACKUP_SETTINGS_UPSELL_FLOW(350),
    PHOTOS_IOS_FACE_CLUSTERING_EXPLICIT_PERMISSION_FLOW(336),
    PHOTOS_IOS_FACE_CLUSTERING_ONBOARDING_DISCLAIMER_FLOW(337),
    PHOTOS_IOS_FACE_CLUSTERING_SETTINGS_FLOW(338),
    PHOTOS_IOS_FACE_CLUSTERING_STANDALONE_DISCLAIMER_FLOW(339),
    PHOTOS_IOS_GOOGLE_ONE_SWITCH_STORAGE_POLICY_FLOW(503),
    PHOTOS_IOS_GPLUS_DOWNLOAD_CONTENT(25),
    PHOTOS_IOS_SHARED_LIBRARY_PROPOSE_FLOW(26),
    PHOTOS_IOS_SHARED_LIBRARY_SETTINGS_FLOW(65),
    PHOTOS_IOS_SHARED_LIBRARY_WITHDRAWAL_FLOW(27),
    PHOTOS_WEB_ALBUM_ARCHIVE_DOWNLOAD_CONTENT(28),
    PHOTOS_WEB_FACE_CLUSTERING_EXPLICIT_PERMISSION_FLOW(340),
    PHOTOS_WEB_FACE_CLUSTERING_ONBOARDING_DISCLAIMER_FLOW(341),
    PHOTOS_WEB_FACE_CLUSTERING_SETTINGS_FLOW(342),
    PHOTOS_WEB_FACE_CLUSTERING_STANDALONE_DISCLAIMER_FLOW(343),
    PHOTOS_WEB_GPLUS_DOWNLOAD_CONTENT(29),
    PHOTOS_WEB_SHARED_LIBRARY_PROPOSE_FLOW(30),
    PHOTOS_WEB_SHARED_LIBRARY_SETTINGS_FLOW(95),
    PHOTOS_WEB_SHARED_LIBRARY_WITHDRAWAL_FLOW(31),
    PLAY_CONSOLE_ANDROID_APP_SETTINGS(9),
    PLAY_CONSOLE_WEB_ADHOC_SHARING_UPLOAD(360),
    PLAY_CONSOLE_WEB_ADHOC_SHARING_UPLOAD_BREWDOG(492),
    PLAY_CONSOLE_WEB_APP_SIGNING_TOS_DIALOG(249),
    PLAY_CONSOLE_WEB_DEVELOPER_SIGN_UP(11),
    PLAY_CONSOLE_WEB_PREFERENCES(10),
    PLAY_CONSOLE_WEB_TEAM_MEMBER_SIGN_UP(12),
    PLAY_CONSOLE_WEB_USER_CONSOLE_TOS(502),
    PLAY_GAMES_SERVICES_ANDROID_APP_WIPEOUT(40),
    PLAY_GAMES_SERVICES_ANDROID_CONSENT_UPDATE_FLOW(37),
    PLAY_GAMES_SERVICES_ANDROID_CREATE_PROFILE_FLOW(36),
    PLAY_GAMES_SERVICES_ANDROID_EDIT_PROFILE_FLOW(47),
    PLAY_GAMES_SERVICES_ANDROID_ENABLE_AUTO_SIGN_IN_FROM_GAME(347),
    PLAY_GAMES_SERVICES_ANDROID_FRIENDS_AND_YOUR_PRIVACY_FLOW(446),
    PLAY_GAMES_SERVICES_ANDROID_FRIENDS_LIST_VISIBILITY_IN_GAME_FLOW(447),
    PLAY_GAMES_SERVICES_ANDROID_PROFILE_WIPEOUT(39),
    PLAY_GAMES_SERVICES_ANDROID_SETTINGS(38),
    PLAY_GAMES_SERVICES_ANDROID_SYSTEM_SETTINGS(50),
    PLAY_GAMES_SERVICES_ANDROID_TV_CREATE_PROFILE_FLOW(48),
    PLAY_GAMES_SERVICES_ANDROID_TV_EDIT_PROFILE_FLOW(49),
    PLAY_GAMES_SERVICES_WEB_CREATE_PROFILE_FLOW(468),
    PLAY_GAMES_SERVICES_WEB_EDIT_PROFILE_FLOW(469),
    PLAY_GAMES_SERVICES_WEB_SETTINGS(482),
    PRESTO_ANDROID_MAESTRO_OOBE_FLOW(444),
    RIDESHARING_GMM_ANDROID_TAXI_TAB_BLOCKING_CONSENT_V1(BaseMfiEventCallback.TYPE_OPSRV_ACCOUNT_ERROR),
    RIDESHARING_GMM_ANDROID_TAXI_TAB_PER_PROVIDER_CONSENT_V1(439),
    RIDESHARING_GMM_IOS_TAXI_TAB_BLOCKING_CONSENT_V1(BaseMfiEventCallback.TYPE_OPSRV_RESULT_ERROR),
    RIDESHARING_GMM_IOS_TAXI_TAB_PER_PROVIDER_CONSENT_V1(440),
    SHARED_ENDORSEMENTS_MY_ACCOUNT_STANDALONE(2),
    SHARED_ENDORSEMENTS_PRIVACY_CHECKUP(3),
    TEST_CONTEXT(1),
    TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_EMAIL_NOTIFICATIONS_TOGGLE(136),
    TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_ITINERARY_TRACKING_TOGGLE(137),
    TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_MDP_TRACKING_TOGGLE(138),
    TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_TRACKED_ITINERARY_TRASH(139),
    TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_TRACKED_MDP_TRASH(140),
    TRAVEL_REENGAGEMENT_WEB_GAMMA_EMAILS_TOGGLE(141),
    TRAVEL_REENGAGEMENT_WEB_HOTEL_SEARCH_MARKET_TRACKING_TOGGLE(145),
    TRAVEL_REENGAGEMENT_WEB_MAYFLOWER_MARKET_TRACKING_TOGGLE(146),
    TRAVEL_REENGAGEMENT_WEB_SEARCH_RESULTS_PAGE_OD_TRACK_BUTTON(507),
    TRAVEL_REENGAGEMENT_WEB_SEARCH_RESULTS_PAGE_OD_UNDO_TRACK_BUTTON(508),
    TRAVEL_REENGAGEMENT_WEB_TRACKED_HOTEL_PRICES_TRASH(147),
    TRAVEL_REENGAGEMENT_WEB_TRAVEL_HOME_PAGE_TRIP_SUGGESTIONS_TOGGLE(148),
    UDC_CONSENT_FLOWS_ANDROID(325),
    UDC_CONSENT_FLOWS_IOS(326),
    UNICORN_EMAIL_OPT_IN_ANDROID_ALL_SET(442),
    UNICORN_EMBEDDED_ACCOUNT_CREATION(45),
    UNICORN_FAMILY_LINK_ACCOUNT_CREATION(96),
    UNICORN_GRADUATION_WEB_UI(6),
    UNICORN_SECONDARY_EDU_ACCOUNT_EMBEDDED_COEXISTENCE(198),
    UNICORN_SECONDARY_EDU_ACCOUNT_EMBEDDED_COEXISTENCE_CHROME_OS(510),
    UNICORN_SIGN_IN_ANDROID_DNP_FLOW(172),
    UNICORN_SIGN_IN_ANDROID_L_DNP_FLOW(55),
    UNICORN_SIGN_IN_CHROME_OS_FLOW(208),
    UNICORN_SIGN_IN_IOS_FLOW(BaseMfiEventCallback.TYPE_ILLEGAL_LINKAGE_DATA),
    UNICORN_SIGN_IN_WEB_FLOW(BaseMfiEventCallback.TYPE_INVALID_LINKAGE_DATA),
    VISTAAR_WEB_ONBOARDING_SIGNUP(314),
    VISTAAR_WEB_ONBOARDING_WHOIS_CONSENT_DIALOG(315),
    WAZE_ANDROID_POPUP(81),
    WAZE_ANDROID_PRIVILEGES(82),
    WAZE_ANDROID_SETTINGS_MENU(83),
    WAZE_ANDROID_SIGNUP(84),
    WAZE_IOS_POPUP(85),
    WAZE_IOS_PRIVILEGES(86),
    WAZE_IOS_SETTINGS_MENU(87),
    WAZE_IOS_SIGNUP(88),
    WAZE_WEB_SETTINGS_MENU(191),
    WEAR_COMPANION_ANDROID_SETTINGS(BaseMfiEventCallback.TYPE_CARD_NOT_ACTIVE),
    WEAR_COMPANION_ANDROID_SETUP_FLOW(BaseMfiEventCallback.TYPE_EXIST_UNKNOWN_CARD),
    WEAR_COMPANION_IOS_SETTINGS(BaseMfiEventCallback.TYPE_ISSUE_LIMIT_EXCEEDED),
    WEAR_COMPANION_IOS_SETUP_FLOW(BaseMfiEventCallback.TYPE_CARD_NOT_UNIQUE),
    WHITE_PAGES_SERVICE_ASSISTANT_COLLECT_PHONE_OUTBOUND_CALLS(407),
    WHITE_PAGES_SERVICE_ASSISTANT_COLLECT_REACHABLE_PHONE(408),
    WHITE_PAGES_SERVICE_COMMON_BROAD_CONSENT(409),
    WHITE_PAGES_SERVICE_COMMON_DISCOVERABILITY_CONSENT(410),
    WHITE_PAGES_SERVICE_COMMON_REACHABILITY_CONSENT(411),
    WHITE_PAGES_SERVICE_GAIA_COLLECT_REACHABLE_PHONE_AFTER_RECOVERY(412),
    WHITE_PAGES_SERVICE_GAIA_COLLECT_REACHABLE_PHONE_REGULAR_SIGN_IN(413),
    YOUNG_TEEN_EMBEDDED_ACCOUNT_CREATION(41),
    YOUTUBE_ANDROID_CHANNEL_CREATION(33),
    YOUTUBE_ANDROID_HISTORY_FEED(179),
    YOUTUBE_ANDROID_MUSIC_STUDENT_PLAN_REDIRECT_TO_SHEERID(281),
    YOUTUBE_ANDROID_PRIVACY_SETTINGS(180),
    YOUTUBE_ANDROID_STUDENT_PLAN_REDIRECT_TO_SHEERID(280),
    YOUTUBE_ANDROID_TOS_BROWSE(396),
    YOUTUBE_ANDROID_TOS_WATCH(391),
    YOUTUBE_CREATOR_STUDIO_WEB_CHANNEL_CREATION(119),
    YOUTUBE_GAMING_ANDROID_ACCOUNT_LINK_SETTINGS(329),
    YOUTUBE_GAMING_ANDROID_ACCOUNT_LINK_WATCH(276),
    YOUTUBE_GAMING_ANDROID_CHANNEL_CREATION(120),
    YOUTUBE_GAMING_IOS_ACCOUNT_LINK_SETTINGS(330),
    YOUTUBE_GAMING_IOS_ACCOUNT_LINK_WATCH(277),
    YOUTUBE_GAMING_IOS_CHANNEL_CREATION(121),
    YOUTUBE_GAMING_MOBILE_WEB_CHANNEL_CREATION(BaseMfiEventCallback.TYPE_OPSRV_REQUIRED_LIB_UNAVAILABLE),
    YOUTUBE_GAMING_MWEB_ACCOUNT_LINK_SETTINGS(364),
    YOUTUBE_GAMING_MWEB_ACCOUNT_LINK_WATCH(356),
    YOUTUBE_GAMING_WEB_ACCOUNT_LINK_SETTINGS(331),
    YOUTUBE_GAMING_WEB_ACCOUNT_LINK_WATCH(265),
    YOUTUBE_GAMING_WEB_CHANNEL_CREATION(122),
    YOUTUBE_IOS_CHANNEL_CREATION(34),
    YOUTUBE_IOS_HISTORY_FEED(181),
    YOUTUBE_IOS_PRIVACY_SETTINGS(182),
    YOUTUBE_IOS_TOS_BROWSE(397),
    YOUTUBE_IOS_TOS_WATCH(392),
    YOUTUBE_MOBILE_WEB_CHANNEL_CREATION(126),
    YOUTUBE_MOBILE_WEB_HISTORY_FEED(248),
    YOUTUBE_MOBILE_WEB_PRIVACY_SETTINGS(298),
    YOUTUBE_MOBILE_WEB_TOS_BROWSE(395),
    YOUTUBE_MOBILE_WEB_TOS_WATCH(390),
    YOUTUBE_MUSIC_ANDROID_ENABLE_LOCATION_RECS_PROMO(ErrorInfo.TYPE_SDU_UNKNOWN),
    YOUTUBE_MUSIC_ANDROID_FINE_LOCATION_DIRECT_ASK(68),
    YOUTUBE_MUSIC_ANDROID_FINE_LOCATION_PROMO(69),
    YOUTUBE_MUSIC_ANDROID_LH_DIRECT_ASK(70),
    YOUTUBE_MUSIC_ANDROID_LH_INFO_MESSAGE(71),
    YOUTUBE_MUSIC_ANDROID_LH_PROMO(72),
    YOUTUBE_MUSIC_ANDROID_SETTINGS(73),
    YOUTUBE_MUSIC_ANDROID_ULR_PROMO(ErrorInfo.TYPE_ACTIVATE_FELICA_HTTP_ERROR),
    YOUTUBE_MUSIC_IOS_ENABLE_LOCATION_RECS_PROMO(BaseMfiEventCallback.TYPE_UNKNOWN_ERROR),
    YOUTUBE_MUSIC_IOS_FINE_LOCATION_DIRECT_ASK(74),
    YOUTUBE_MUSIC_IOS_FINE_LOCATION_PROMO(75),
    YOUTUBE_MUSIC_IOS_SETTINGS(76),
    YOUTUBE_MUSIC_WEB_LH_DIRECT_ASK(77),
    YOUTUBE_MUSIC_WEB_LH_INFO_MESSAGE(78),
    YOUTUBE_MUSIC_WEB_LH_PROMO(79),
    YOUTUBE_MUSIC_WEB_PREF_VALUE_MIGRATION(406),
    YOUTUBE_MUSIC_WEB_SETTINGS(80),
    YOUTUBE_MUSIC_WEB_TOS_UPLOAD(488),
    YOUTUBE_MWEB_STUDENT_PLAN_REDIRECT_TO_SHEERID(283),
    YOUTUBE_WEB_BRAND_ACCOUNT_CHANNEL_CREATION(204),
    YOUTUBE_WEB_BRAND_ACCOUNT_CHANNEL_CREATION_V2(433),
    YOUTUBE_WEB_CHANNEL_CREATION(35),
    YOUTUBE_WEB_HISTORY_CONTROLS(BaseMfiEventCallback.TYPE_INTERRUPTED_ERROR),
    YOUTUBE_WEB_HISTORY_FEED(183),
    YOUTUBE_WEB_REMIX_PRIVACY_SETTINGS(244),
    YOUTUBE_WEB_REMIX_STUDENT_PLAN_REDIRECT_TO_SHEERID(282),
    YOUTUBE_WEB_STUDENT_PLAN_REDIRECT_TO_SHEERID(279),
    YOUTUBE_WEB_TOS_BROWSE(394),
    YOUTUBE_WEB_TOS_WATCH(389),
    YOUTUBE_WEB_WHAT_TO_WATCH_FEED(317),
    CROWDSOURCE_WEB_LEADERBOARDS_CONSENT_SCREEN(404),
    CROWDSOURCE_WEB_SETTINGS_UI(405),
    PHOTOS_ANDROID_FACE_CLUSTERING_OPT_IN_FLOW(290),
    PHOTOS_ANDROID_FACE_CLUSTERING_OPT_OUT_FLOW(308),
    PHOTOS_IOS_FACE_CLUSTERING_OPT_IN_FLOW(291),
    PHOTOS_IOS_FACE_CLUSTERING_OPT_OUT_FLOW(309),
    PHOTOS_WEB_FACE_CLUSTERING_OPT_IN_FLOW(292),
    PHOTOS_WEB_FACE_CLUSTERING_OPT_OUT_FLOW(310),
    YOUTUBE_GAMING_WEB_GAMING_ACCOUNT_LINK_WATCH(278);
    

    /* renamed from: iC */
    public final int f145962iC;

    private bsmx(int i) {
        this.f145962iC = i;
    }

    /* renamed from: a */
    public static bsmx m115993a(int i) {
        switch (i) {
            case 0:
                return CONTEXT_ID_UNSPECIFIED;
            case 1:
                return TEST_CONTEXT;
            case 2:
                return SHARED_ENDORSEMENTS_MY_ACCOUNT_STANDALONE;
            case 3:
                return SHARED_ENDORSEMENTS_PRIVACY_CHECKUP;
            case 4:
                return CONSTELLATION_CONSENT_MINUTEMAID_SETUP_WIZARD;
            case 5:
                return CONSTELLATION_CONSENT_GMSCORE_SETTINGS_UI;
            case 6:
                return UNICORN_GRADUATION_WEB_UI;
            case 7:
                return MINUTEMAID_SIGN_UP;
            case 8:
                return ANDROID_SETUP_WIZARD_GOOGLE_SERVICES;
            case 9:
                return PLAY_CONSOLE_ANDROID_APP_SETTINGS;
            case 10:
                return PLAY_CONSOLE_WEB_PREFERENCES;
            case 11:
                return PLAY_CONSOLE_WEB_DEVELOPER_SIGN_UP;
            case 12:
                return PLAY_CONSOLE_WEB_TEAM_MEMBER_SIGN_UP;
            case 13:
                return MINUTEMAID_ADD_PHONE_SPEED_BUMP;
            case 14:
                return ANDROID_BACKUP_SET_BACKUP_ACCOUNT;
            case 15:
                return ANDROID_BACKUP_OPTIN;
            case 16:
                return ANDROID_BACKUP_DRIVE_BACKUP_SETTINGS;
            case 17:
                return ANDROID_BACKUP_SET_BACKUP_ACCOUNT_FLOW;
            case 18:
                return ANDROID_SETUP_WIZARD_GOOGLE_SERVICES_ADD_ACCOUNT;
            case 19:
                return GOOGLE_PAY_GMSCORE_TAPANDPAY_SETTINGS;
            case 20:
                return GOOGLE_PAY_GMSCORE_TAPANDPAY_SECOND_PARTY_TOKENIZATION_CONFIRMATION;
            case 21:
                return LOCATION_SHARING_ANDROID_TOS_SCREEN;
            case 22:
                return PHOTOS_ANDROID_GPLUS_DOWNLOAD_CONTENT;
            case 23:
                return PHOTOS_ANDROID_SHARED_LIBRARY_PROPOSE_FLOW;
            case 24:
                return PHOTOS_ANDROID_SHARED_LIBRARY_WITHDRAWAL_FLOW;
            case 25:
                return PHOTOS_IOS_GPLUS_DOWNLOAD_CONTENT;
            case 26:
                return PHOTOS_IOS_SHARED_LIBRARY_PROPOSE_FLOW;
            case 27:
                return PHOTOS_IOS_SHARED_LIBRARY_WITHDRAWAL_FLOW;
            case 28:
                return PHOTOS_WEB_ALBUM_ARCHIVE_DOWNLOAD_CONTENT;
            case 29:
                return PHOTOS_WEB_GPLUS_DOWNLOAD_CONTENT;
            case 30:
                return PHOTOS_WEB_SHARED_LIBRARY_PROPOSE_FLOW;
            case 31:
                return PHOTOS_WEB_SHARED_LIBRARY_WITHDRAWAL_FLOW;
            case 32:
                return ANDROID_TV_SETUP_WIZARD_FLOW;
            case 33:
                return YOUTUBE_ANDROID_CHANNEL_CREATION;
            case 34:
                return YOUTUBE_IOS_CHANNEL_CREATION;
            case 35:
                return YOUTUBE_WEB_CHANNEL_CREATION;
            case 36:
                return PLAY_GAMES_SERVICES_ANDROID_CREATE_PROFILE_FLOW;
            case FelicaException.TYPE_NOT_CLOSED:
                return PLAY_GAMES_SERVICES_ANDROID_CONSENT_UPDATE_FLOW;
            case FelicaException.TYPE_ILLEGAL_METHOD_CALL:
                return PLAY_GAMES_SERVICES_ANDROID_SETTINGS;
            case FelicaException.TYPE_USED_BY_OTHER_APP:
                return PLAY_GAMES_SERVICES_ANDROID_PROFILE_WIPEOUT;
            case FelicaException.TYPE_PUSH_FAILED:
                return PLAY_GAMES_SERVICES_ANDROID_APP_WIPEOUT;
            case 41:
                return YOUNG_TEEN_EMBEDDED_ACCOUNT_CREATION;
            case FelicaException.TYPE_ALREADY_ACTIVATED:
                return GOOGLE_ASSISTANT_ANDROID_CONSENT_UI;
            case FelicaException.TYPE_GET_BLOCK_COUNT_INFORMATION_FAILED:
                return GOOGLE_ASSISTANT_ANDROID_CONFIRM_REJECT;
            case FelicaException.TYPE_RESET_FAILED:
                return FAMILIES_ANDROID_FAMILY_CREATION;
            case FelicaException.TYPE_GET_SYSTEM_CODE_LIST_FAILED:
                return UNICORN_EMBEDDED_ACCOUNT_CREATION;
            case FelicaException.TYPE_GET_CONTAINER_ID_FAILED:
                return ANDROID_LOCATION_SERVICES_CONSENT_UI;
            case 47:
                return PLAY_GAMES_SERVICES_ANDROID_EDIT_PROFILE_FLOW;
            case 48:
                return PLAY_GAMES_SERVICES_ANDROID_TV_CREATE_PROFILE_FLOW;
            case FelicaException.TYPE_CURRENTLY_ACTIVATING:
                return PLAY_GAMES_SERVICES_ANDROID_TV_EDIT_PROFILE_FLOW;
            case 50:
                return PLAY_GAMES_SERVICES_ANDROID_SYSTEM_SETTINGS;
            case 51:
                return PHOTOS_ANDROID_AUTOBACKUP_CONVERSION_SHEET_FLOW;
            case 52:
                return PHOTOS_ANDROID_AUTOBACKUP_ENABLE_BACKUP_SHEET_FLOW;
            case 53:
                return PHOTOS_ANDROID_AUTOBACKUP_ONBOARDING_SHEET_FLOW;
            case 54:
                return PHOTOS_ANDROID_AUTOBACKUP_SETTINGS_FLOW;
            case 55:
                return UNICORN_SIGN_IN_ANDROID_L_DNP_FLOW;
            case FelicaException.TYPE_ACTIVATE_FAILED:
                return MADDEN_WEB_FINALIZE_BOOKING_FLOW;
            case 57:
                return LOCATION_SHARING_IOS_TOS_SCREEN;
            case FelicaException.TYPE_OFFLINE_CANCELED:
                return GOOGLE_ASSISTANT_IOS_CONSENT_UI;
            case FelicaException.TYPE_NOW_EXECUTING_FALP:
                return GOOGLE_ASSISTANT_IOS_CONFIRM_REJECT;
            case FelicaException.TYPE_MFC_NOT_FOUND:
                return PHOTOS_IOS_AUTOBACKUP_ENABLE_BACKUP_FLOW;
            case FelicaException.TYPE_INITIATE_ADHOC_ERROR:
                return PHOTOS_IOS_AUTOBACKUP_ONBOARDING_FLOW;
            case 62:
                return PHOTOS_IOS_AUTOBACKUP_SETTINGS_FLOW;
            case 63:
                return PAYMENTS_EMBEDDED_BUY_FLOW;
            case 64:
                return PAYMENTS_EMBEDDED_INSTRUMENT_MANAGER;
            case KeyInformation.AES128_DES56:
                return PHOTOS_IOS_SHARED_LIBRARY_SETTINGS_FLOW;
            case 66:
                return CHROME_SYNC_SETUP_CONSENT_DIALOG;
            case KeyInformation.AES128_DES112:
                return PERIODIC_PERSONALIZATION_REMINDERS_PRIVACY_CHECKUP;
            case 68:
                return YOUTUBE_MUSIC_ANDROID_FINE_LOCATION_DIRECT_ASK;
            case 69:
                return YOUTUBE_MUSIC_ANDROID_FINE_LOCATION_PROMO;
            case 70:
                return YOUTUBE_MUSIC_ANDROID_LH_DIRECT_ASK;
            case 71:
                return YOUTUBE_MUSIC_ANDROID_LH_INFO_MESSAGE;
            case 72:
                return YOUTUBE_MUSIC_ANDROID_LH_PROMO;
            case 73:
                return YOUTUBE_MUSIC_ANDROID_SETTINGS;
            case 74:
                return YOUTUBE_MUSIC_IOS_FINE_LOCATION_DIRECT_ASK;
            case 75:
                return YOUTUBE_MUSIC_IOS_FINE_LOCATION_PROMO;
            case 76:
                return YOUTUBE_MUSIC_IOS_SETTINGS;
            case 77:
                return YOUTUBE_MUSIC_WEB_LH_DIRECT_ASK;
            case 78:
                return YOUTUBE_MUSIC_WEB_LH_INFO_MESSAGE;
            case KeyInformation.AES128:
                return YOUTUBE_MUSIC_WEB_LH_PROMO;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_LONG_MESSAGE /*80*/:
                return YOUTUBE_MUSIC_WEB_SETTINGS;
            case 81:
                return WAZE_ANDROID_POPUP;
            case 82:
                return WAZE_ANDROID_PRIVILEGES;
            case 83:
                return WAZE_ANDROID_SETTINGS_MENU;
            case 84:
                return WAZE_ANDROID_SIGNUP;
            case 85:
                return WAZE_IOS_POPUP;
            case 86:
                return WAZE_IOS_PRIVILEGES;
            case 87:
                return WAZE_IOS_SETTINGS_MENU;
            case 88:
                return WAZE_IOS_SIGNUP;
            case 89:
                return GOOGLE_PAY_ANDROID_LADDER_PROMOTION_CONSENT_UI;
            case 90:
                return GOOGLE_PAY_ANDROID_REFERRAL_INVITATION_UI;
            case 91:
                return GOOGLE_PAY_ANDROID_REFERRAL_PROMO_CODE_APPLIED_UI;
            case 92:
                return GOOGLE_PAY_GMSCORE_TAPANDPAY_VISA_CHECKOUT_LINKING_UI;
            case 93:
                return GOOGLE_PAY_ANDROID_APP_SETTINGS;
            case 94:
                return PHOTOS_ANDROID_SHARED_LIBRARY_SETTINGS_FLOW;
            case 95:
                return PHOTOS_WEB_SHARED_LIBRARY_SETTINGS_FLOW;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PERSON_NAME /*96*/:
                return UNICORN_FAMILY_LINK_ACCOUNT_CREATION;
            case 97:
                return GOOGLE_HOME_ANDROID_ASSISTANT_SETTINGS;
            case 98:
                return GOOGLE_HOME_ANDROID_DEVICE_SETTINGS;
            case 99:
                return GOOGLE_HOME_ANDROID_EMAIL_NOTIFICATIONS_SETTINGS;
            case 100:
                return GOOGLE_HOME_ANDROID_FIRST_RUN;
            case 101:
                return GOOGLE_HOME_ANDROID_OOBE_FLOW;
            case 102:
                return GOOGLE_HOME_IOS_ASSISTANT_SETTINGS;
            case ErrorInfo.TYPE_SDU_COMMUNICATIONERROR:
                return GOOGLE_HOME_IOS_DEVICE_OR_ACCOUNT_LEVEL_SETTINGS_SEE_BUG_116807852;
            case ErrorInfo.TYPE_SDU_FAILED:
                return GOOGLE_HOME_IOS_EMAIL_NOTIFICATIONS_SETTINGS;
            case ErrorInfo.TYPE_SDU_MEMORY_FULL:
                return GOOGLE_HOME_IOS_FIRST_RUN;
            case 106:
                return GOOGLE_HOME_IOS_OOBE_FLOW;
            case 107:
                return GOOGLE_WIFI_ANDROID_EMAIL_NOTIFICATIONS_SETTINGS;
            case 108:
                return GOOGLE_WIFI_ANDROID_OOBE_FLOW;
            case 109:
                return GOOGLE_WIFI_ANDROID_PRIVACY_SETTINGS;
            case 110:
                return GOOGLE_WIFI_IOS_EMAIL_NOTIFICATIONS_SETTINGS;
            case 111:
                return GOOGLE_WIFI_IOS_OOBE_FLOW;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_POSTAL_ADDRESS /*112*/:
                return GOOGLE_WIFI_IOS_PRIVACY_SETTINGS;
            case 113:
                return DRIVE_IOS_SETTINGS_BACKUP_FLOW;
            case 114:
                return PAYMENTS_EMBEDDED_ADD_INSTRUMENT;
            case 115:
                return PAYMENTS_EMBEDDED_FIX_INSTRUMENT;
            case 116:
                return PAYMENTS_EMBEDDED_IDENTITY_AND_CREDIT;
            case 117:
                return PAYMENTS_EMBEDDED_INTEGRATOR_API;
            case 118:
                return PAYMENTS_EMBEDDED_UPSTREAM;
            case 119:
                return YOUTUBE_CREATOR_STUDIO_WEB_CHANNEL_CREATION;
            case 120:
                return YOUTUBE_GAMING_ANDROID_CHANNEL_CREATION;
            case 121:
                return YOUTUBE_GAMING_IOS_CHANNEL_CREATION;
            case 122:
                return YOUTUBE_GAMING_WEB_CHANNEL_CREATION;
            case 123:
                return PHONE_TO_GAIA_ANDROID_NOTIFICATION;
            case 124:
                return ANDROID_SETUP_WIZARD_PIXEL_TOS_DEFERRED_SETUP;
            case 125:
                return ANDROID_SETUP_WIZARD_PIXEL_TOS_INITIAL_SETUP;
            case 126:
                return YOUTUBE_MOBILE_WEB_CHANNEL_CREATION;
            case 127:
                return CLOUD_CONSOLE_WEB_PERSONALIZATION_SETTINGS;
            case 128:
                return LOCATION_HISTORY_IOS_SETTINGS_UI;
            case 129:
                return ANDROID_WIFI_SCAN_SETTINGS_UPDATE_PRE_P_CONSENT;
            default:
                switch (i) {
                    case 136:
                        return TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_EMAIL_NOTIFICATIONS_TOGGLE;
                    case 137:
                        return TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_ITINERARY_TRACKING_TOGGLE;
                    case 138:
                        return TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_MDP_TRACKING_TOGGLE;
                    case 139:
                        return TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_TRACKED_ITINERARY_TRASH;
                    case 140:
                        return TRAVEL_REENGAGEMENT_WEB_FLIGHT_SEARCH_TRACKED_MDP_TRASH;
                    case 141:
                        return TRAVEL_REENGAGEMENT_WEB_GAMMA_EMAILS_TOGGLE;
                    default:
                        switch (i) {
                            case 145:
                                return TRAVEL_REENGAGEMENT_WEB_HOTEL_SEARCH_MARKET_TRACKING_TOGGLE;
                            case 146:
                                return TRAVEL_REENGAGEMENT_WEB_MAYFLOWER_MARKET_TRACKING_TOGGLE;
                            case 147:
                                return TRAVEL_REENGAGEMENT_WEB_TRACKED_HOTEL_PRICES_TRASH;
                            case 148:
                                return TRAVEL_REENGAGEMENT_WEB_TRAVEL_HOME_PAGE_TRIP_SUGGESTIONS_TOGGLE;
                            case 149:
                                return GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_ONBOARDING_STANDALONE;
                            case MfiClientException.TYPE_MFICLIENT_REMOTE_ACCESS_FAILED:
                                return GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_ONBOARDING_WITH_VOICE_MATCH;
                            case MfiClientException.TYPE_MFICLIENT_NOT_FOUND:
                                return GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_SETTINGS;
                            case MfiClientException.TYPE_MFICLIENT_NOT_ACTIVATED:
                                return GOOGLE_ASSISTANT_ANDROID_VOICE_MATCH_ONBOARDING_GOOGLE_HOME;
                            case MfiClientException.TYPE_MFICLIENT_STARTED:
                                return GOOGLE_ASSISTANT_ANDROID_VOICE_MATCH_ONBOARDING_OPA_ANDROID;
                            case MfiClientException.TYPE_MFICLIENT_NOT_STARTED:
                                return GOOGLE_ASSISTANT_ANDROID_VOICE_MATCH_SETTINGS;
                            case MfiClientException.TYPE_ILLEGAL_LINKAGE_DATA:
                                return GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_ONBOARDING_STANDALONE;
                            case MfiClientException.TYPE_NO_ACCOUNT_INFO:
                                return GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_ONBOARDING_WITH_VOICE_MATCH;
                            case MfiClientException.TYPE_CARD_NOT_CACHED:
                                return GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_SETTINGS;
                            case MfiClientException.TYPE_ILLEGAL_CARD_OPERATION:
                                return GOOGLE_ASSISTANT_IOS_VOICE_MATCH_ONBOARDING_GOOGLE_HOME;
                            case MfiClientException.TYPE_MFICLIENT_CURRENTLY_ONLINE:
                                return GOOGLE_ASSISTANT_IOS_VOICE_MATCH_ONBOARDING_OPA_IOS;
                            case 160:
                                return GOOGLE_ASSISTANT_IOS_VOICE_MATCH_SETTINGS;
                            case 161:
                                return APPLIED_CS_WITH_ANDROID_WEB_USER_REGISTRATION;
                            case 162:
                                return PAYMENTS_EMBEDDED_VERIFICATION;
                            case 163:
                                return GOOGLE_HOME_IOS_APP_CRASH_UPLOAD_CONSENT_DIALOG;
                            case 164:
                                return FAMILYLINK_ANDROID_DEVICE_SETTINGS_UI;
                            case 165:
                                return FAMILYLINK_IOS_DEVICE_SETTINGS_UI;
                            case 166:
                                return FAMILYLINK_WEB_DEVICE_SETTINGS_UI;
                            case 167:
                                return GOOGLE_HOME_ANDROID_BROWSE_CONTENT_DETAILS_VIEW;
                            case 168:
                                return GOOGLE_HOME_ANDROID_BROWSE_SHELVES_VIEW;
                            case 169:
                                return GOOGLE_HOME_ANDROID_CONNECTED_ACCOUNTS_SETTINGS;
                            case 170:
                                return GOOGLE_HOME_IOS_BROWSE_SHELVES_VIEW;
                            case 171:
                                return GOOGLE_HOME_IOS_CONNECTED_ACCOUNTS_SETTINGS;
                            case 172:
                                return UNICORN_SIGN_IN_ANDROID_DNP_FLOW;
                            case 173:
                                return FAMILIES_ANDROID_FAMILYLINK_ONBOARDING_V1;
                            case 174:
                                return FAMILIES_ANDROID_FAMILYLINK_ONBOARDING_V2;
                            case 175:
                                return FAMILIES_IOS_FAMILYLINK_ONBOARDING_V1;
                            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_FILTER /*176*/:
                                return FAMILIES_IOS_FAMILYLINK_ONBOARDING_V2;
                            case 177:
                                return DOMAIN_REGISTRAR_WEB_MANAGE_DOMAINS_WHOIS_CONSENT_FLOW;
                            case 178:
                                return DOMAIN_REGISTRAR_WEB_REGISTRATION_WHOIS_CONSENT_FLOW;
                            case 179:
                                return YOUTUBE_ANDROID_HISTORY_FEED;
                            case 180:
                                return YOUTUBE_ANDROID_PRIVACY_SETTINGS;
                            case 181:
                                return YOUTUBE_IOS_HISTORY_FEED;
                            case 182:
                                return YOUTUBE_IOS_PRIVACY_SETTINGS;
                            case 183:
                                return YOUTUBE_WEB_HISTORY_FEED;
                            case 184:
                                return FAMILYLINK_ANDROID_LOCATION_CONSENT_UI;
                            case 185:
                                return FAMILYLINK_IOS_LOCATION_CONSENT_UI;
                            case 186:
                                return FREIGHTER_ANDROID_LANDING_SCREEN_POP_UP;
                            case 187:
                                return FREIGHTER_ANDROID_SETTINGS;
                            case 188:
                                return CROWDSOURCE_ANDROID_SETTINGS_UI;
                            case 189:
                                return CROWDSOURCE_ANDROID_IMAGE_CAPTURE_CONSENT_SCREEN;
                            case 190:
                                return CROWDSOURCE_ANDROID_IMAGE_CAPTURE_OPENSOURCE_DIALOG;
                            case 191:
                                return WAZE_WEB_SETTINGS_MENU;
                            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PHONETIC /*192*/:
                                return DRIVE_ANDROID_SETTINGS;
                            default:
                                switch (i) {
                                    case 198:
                                        return UNICORN_SECONDARY_EDU_ACCOUNT_EMBEDDED_COEXISTENCE;
                                    case ErrorInfo.TYPE_SDU_UNKNOWN:
                                        return YOUTUBE_MUSIC_ANDROID_ENABLE_LOCATION_RECS_PROMO;
                                    case BaseMfiEventCallback.TYPE_UNKNOWN_ERROR:
                                        return YOUTUBE_MUSIC_IOS_ENABLE_LOCATION_RECS_PROMO;
                                    case ErrorInfo.TYPE_ACTIVATE_FELICA_HTTP_ERROR:
                                        return YOUTUBE_MUSIC_ANDROID_ULR_PROMO;
                                    case 202:
                                        return CHROME_OS_ARC_SETUP_DIALOG;
                                    case 203:
                                        return PAYMENTS_EMBEDDED_UNAUTHORIZED_TRANSACTIONS;
                                    case 204:
                                        return YOUTUBE_WEB_BRAND_ACCOUNT_CHANNEL_CREATION;
                                    case 205:
                                        return PAYMENTS_EMBEDDED_SETTINGS;
                                    case BaseMfiEventCallback.TYPE_SERVER_GENERAL_ERROR:
                                        return PAYMENTS_EMBEDDED_ONLINE_CLICK_TO_ACCEPT;
                                    case BaseMfiEventCallback.TYPE_EXPIRED_MFI:
                                        return PAYMENTS_EMBEDDED_TAX_COLLECTION;
                                    case 208:
                                        return UNICORN_SIGN_IN_CHROME_OS_FLOW;
                                    case BaseMfiEventCallback.TYPE_ILLEGAL_LINKAGE_DATA:
                                        return UNICORN_SIGN_IN_IOS_FLOW;
                                    case BaseMfiEventCallback.TYPE_INVALID_LINKAGE_DATA:
                                        return UNICORN_SIGN_IN_WEB_FLOW;
                                    case BaseMfiEventCallback.TYPE_CARD_NOT_ACTIVE:
                                        return WEAR_COMPANION_ANDROID_SETTINGS;
                                    case BaseMfiEventCallback.TYPE_EXIST_UNKNOWN_CARD:
                                        return WEAR_COMPANION_ANDROID_SETUP_FLOW;
                                    case BaseMfiEventCallback.TYPE_ISSUE_LIMIT_EXCEEDED:
                                        return WEAR_COMPANION_IOS_SETTINGS;
                                    case BaseMfiEventCallback.TYPE_CARD_NOT_UNIQUE:
                                        return WEAR_COMPANION_IOS_SETUP_FLOW;
                                    case BaseMfiEventCallback.TYPE_INTERRUPTED_ERROR:
                                        return YOUTUBE_WEB_HISTORY_CONTROLS;
                                    case BaseMfiEventCallback.TYPE_OPSRV_ACCOUNT_ERROR:
                                        return RIDESHARING_GMM_ANDROID_TAXI_TAB_BLOCKING_CONSENT_V1;
                                    case BaseMfiEventCallback.TYPE_OPSRV_RESULT_ERROR:
                                        return RIDESHARING_GMM_IOS_TAXI_TAB_BLOCKING_CONSENT_V1;
                                    case BaseMfiEventCallback.TYPE_AGREEMENT_NOT_ACCEPT:
                                        return GOOGLE_PAY_ANDROID_LIVE_FEED_CARD;
                                    case BaseMfiEventCallback.TYPE_OPSRV_REQUIRED_LIB_UNAVAILABLE:
                                        return YOUTUBE_GAMING_MOBILE_WEB_CHANNEL_CREATION;
                                    case 220:
                                        return MINUTEMAID_SIGN_IN_CONSENT_SPEED_BUMP;
                                    case 221:
                                        return OFFLINE_RECEIPTS_ANDROID_MAPS_TIMELINE_OPT_IN_FLOW;
                                    case 222:
                                        return CONSENT_CAMPAIGN_CONSENT_BUMP_1;
                                    case 223:
                                        return CONSENT_CAMPAIGN_CONSENT_BUMP_2;
                                    case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_WEB_PASSWORD /*224*/:
                                        return GAIA_WEB_SIGNUP;
                                    case 225:
                                        return DUO_ANDROID_EXISTING_USER_BUMP_FROM_NOTIFICATION;
                                    case 226:
                                        return DUO_ANDROID_EXISTING_USER_BUMP_FROM_SETTINGS;
                                    case 227:
                                        return DUO_ANDROID_NEW_USER_SETUP_FLOW;
                                    case 228:
                                        return DUO_IOS_EXISTING_USER_BUMP_FROM_NOTIFICATION;
                                    case 229:
                                        return DUO_IOS_EXISTING_USER_BUMP_FROM_SETTINGS;
                                    case 230:
                                        return DUO_IOS_NEW_USER_SETUP_FLOW;
                                    case 231:
                                        return GOOGLE_PAY_IOS_APP_SETTINGS;
                                    case 232:
                                        return GOOGLE_PAY_IOS_LIVE_FEED_CARD;
                                    case 233:
                                        return GOOGLE_ASSISTANT_ANDROID_DUO_ACCOUNT_LEVEL_SETTINGS;
                                    case 234:
                                        return GOOGLE_ASSISTANT_ANDROID_DUO_DEVICE_LEVEL_SETTINGS;
                                    case 235:
                                        return GOOGLE_ASSISTANT_IOS_DUO_ACCOUNT_LEVEL_SETTINGS;
                                    case 236:
                                        return GOOGLE_ASSISTANT_IOS_DUO_DEVICE_LEVEL_SETTINGS;
                                    case 237:
                                        return FITNESS_ANDROID_ONBOARDING_FLOW;
                                    case 238:
                                        return FITNESS_ANDROID_SETTINGS_UI;
                                    case 239:
                                        return GOOGLE_PAY_ANDROID_PAYMENT_METHOD_DETAILS;
                                    case 240:
                                        return GOOGLE_PAY_ANDROID_LANDING_SCREEN;
                                    case 241:
                                        return GOOGLE_PAY_ANDROID_REFERRAL_PROMO_CODE_ENTRY_UI;
                                    case 242:
                                        return CHROME_OS_ARC_REMOVE_ALL_ANDROID_APPS_DIALOG;
                                    case 243:
                                        return CLOUD_TALENT_SOLUTION_DATA_WEB_LOGGING_SETTINGS;
                                    case 244:
                                        return YOUTUBE_WEB_REMIX_PRIVACY_SETTINGS;
                                    case 245:
                                        return HANCOCK_SIGN_UP;
                                    case 246:
                                        return DUO_ANDROID_REWARDS_ONBOARDING_FLOW;
                                    case 247:
                                        return DUO_IOS_REWARDS_ONBOARDING_FLOW;
                                    case 248:
                                        return YOUTUBE_MOBILE_WEB_HISTORY_FEED;
                                    case 249:
                                        return PLAY_CONSOLE_WEB_APP_SIGNING_TOS_DIALOG;
                                    case 250:
                                        return GOOGLE_ACCOUNT_WEB_PRIVACY_CHECKUP;
                                    case 251:
                                        return GOOGLE_ACCOUNT_WEB_WHITEPAGES_UI;
                                    case 252:
                                        return CHROME_UNIFIED_CONSENT_DIALOG;
                                    case 253:
                                        return GOOGLE_HOME_ANDROID_NEW_MANAGER_OOBE_FLOW;
                                    case 254:
                                        return GOOGLE_HOME_IOS_NEW_MANAGER_OOBE_FLOW;
                                    case 255:
                                        return FAMILYLINK_ANDROID_KIDS_MODULE_SUPERVISION_OPTIN_UI;
                                    case PSKKeyManager.MAX_KEY_LENGTH_BYTES:
                                        return FAMILYLINK_ANDROID_KIDS_MODULE_SUPERVISION_OPTOUT_UI;
                                    case 257:
                                        return FAMILYLINK_ANDROID_SUPERVISION_OPTOUT_UI;
                                    case 258:
                                        return FAMILYLINK_IOS_SUPERVISION_OPTOUT_UI;
                                    case 259:
                                        return ANDROID_AUTO_SETUP_WIZARD_GOOGLE_SERVICES;
                                    case 260:
                                        return ANDROID_AUTO_SETUP_WIZARD_GOOGLE_SERVICES_ADD_ACCOUNT;
                                    case 261:
                                        return GOOGLE_HOME_ANDROID_INVITEE_INITIATED_INVITE;
                                    case 262:
                                        return GOOGLE_HOME_ANDROID_MANAGER_INITIATED_INVITE;
                                    case 263:
                                        return GOOGLE_HOME_IOS_INVITEE_INITIATED_INVITE;
                                    case 264:
                                        return GOOGLE_HOME_IOS_MANAGER_INITIATED_INVITE;
                                    case 265:
                                        return YOUTUBE_GAMING_WEB_ACCOUNT_LINK_WATCH;
                                    case 266:
                                        return GOOGLE_PAY_WEB_GAMMA_OPT_OUT_PAGE;
                                    case 267:
                                        return GOOGLE_PAY_WEB_SETTINGS;
                                    case 268:
                                        return GOOGLE_ONE_ANDROID_FAMILY_SHARING_SETTING;
                                    case 269:
                                        return GOOGLE_ONE_ANDROID_MARKETING_SETTING;
                                    case 270:
                                        return GOOGLE_ONE_ANDROID_PURCHASE_FLOW;
                                    case 271:
                                        return GOOGLE_ONE_MARKETING_CONFIRMATION_EMAIL;
                                    case 272:
                                        return GOOGLE_ONE_WEB_FAMILY_SHARING_SETTING;
                                    case 273:
                                        return GOOGLE_ONE_WEB_INITIAL_MARKETING_SETTING;
                                    case 274:
                                        return GOOGLE_ONE_WEB_MARKETING_SETTING;
                                    case 275:
                                        return GOOGLE_ONE_WEB_PURCHASE_FLOW;
                                    case 276:
                                        return YOUTUBE_GAMING_ANDROID_ACCOUNT_LINK_WATCH;
                                    case 277:
                                        return YOUTUBE_GAMING_IOS_ACCOUNT_LINK_WATCH;
                                    case 278:
                                        return YOUTUBE_GAMING_WEB_GAMING_ACCOUNT_LINK_WATCH;
                                    case 279:
                                        return YOUTUBE_WEB_STUDENT_PLAN_REDIRECT_TO_SHEERID;
                                    case 280:
                                        return YOUTUBE_ANDROID_STUDENT_PLAN_REDIRECT_TO_SHEERID;
                                    case 281:
                                        return YOUTUBE_ANDROID_MUSIC_STUDENT_PLAN_REDIRECT_TO_SHEERID;
                                    case 282:
                                        return YOUTUBE_WEB_REMIX_STUDENT_PLAN_REDIRECT_TO_SHEERID;
                                    case 283:
                                        return YOUTUBE_MWEB_STUDENT_PLAN_REDIRECT_TO_SHEERID;
                                    case 284:
                                        return FAMILYLINK_WEB_SUPERVISION_OPTIN_UI;
                                    case 285:
                                        return GOOGLE_ONE_WEB_FAMILY_SHARING_SETTING_LANDING_PAGE;
                                    case 286:
                                        return GBOARD_ANDROID_TYPING_HISTORY_SYNC;
                                    case 287:
                                        return GOOGLE_ASSISTANT_CROS_CONSENT_UI;
                                    case 288:
                                        return GOOGLE_ONE_ANDROID_FAMILY_SHARING_SETTING_HOME_TAB;
                                    case 289:
                                        return NETAPP_CLOUD_VOLUMES_WEB_THIRD_PARTY_NOTICE_CONSENT;
                                    case 290:
                                        return PHOTOS_ANDROID_FACE_CLUSTERING_OPT_IN_FLOW;
                                    case 291:
                                        return PHOTOS_IOS_FACE_CLUSTERING_OPT_IN_FLOW;
                                    case 292:
                                        return PHOTOS_WEB_FACE_CLUSTERING_OPT_IN_FLOW;
                                    case 293:
                                        return GOOGLE_PAY_ANDROID_VALUABLE_SIGNUP_UI;
                                    case 294:
                                        return GOOGLE_HOME_IOS_DEVICE_SETTINGS;
                                    case 295:
                                        return GOOGLE_PAY_GMSCORE_TAPANDPAY_PROMOTION_NOTIFICATION;
                                    case 296:
                                        return BQ_DTS_WEB_CREATE_CONFIG;
                                    case 297:
                                        return BQ_DTS_WEB_EDIT_CONFIG;
                                    case 298:
                                        return YOUTUBE_MOBILE_WEB_PRIVACY_SETTINGS;
                                    case ErrorInfo.TYPE_ACTIVATE_FELICA_UNKNOWN_ERROR:
                                        return MADDEN_WEB_JOIN_WAITLIST_FLOW;
                                    case 300:
                                        return GOOGLE_SHOPPING_TRANSACTION_ANDROID_ORDER_CREATION;
                                    case ErrorInfo.TYPE_FSC_HTTP_ERROR:
                                        return GOOGLE_SHOPPING_TRANSACTION_IOS_ORDER_CREATION;
                                    case 302:
                                        return GOOGLE_SHOPPING_TRANSACTION_WEB_ORDER_CREATION;
                                    case 303:
                                        return ITHACA_WEB_USER_OPT_OUT;
                                    case 304:
                                        return ITHACA_WEB_USER_SIGN_UP;
                                    case 305:
                                        return FITNESS_IOS_ONBOARDING_FLOW;
                                    case 306:
                                        return FITNESS_IOS_SETTINGS_UI;
                                    case 307:
                                        return GCP_MARKETPLACE_DEPLOYMENT_CONFIG;
                                    case 308:
                                        return PHOTOS_ANDROID_FACE_CLUSTERING_OPT_OUT_FLOW;
                                    case 309:
                                        return PHOTOS_IOS_FACE_CLUSTERING_OPT_OUT_FLOW;
                                    case 310:
                                        return PHOTOS_WEB_FACE_CLUSTERING_OPT_OUT_FLOW;
                                    case 311:
                                        return MOBILE_CONSENT_FLOWS_ANDROID_LOHIBOSHE_DEMO;
                                    case 312:
                                        return DRIVE_WEB_SETTINGS;
                                    case 313:
                                        return PAISA_MERCHANT_ANDROID_REGISTRATION_FLOW;
                                    case 314:
                                        return VISTAAR_WEB_ONBOARDING_SIGNUP;
                                    case 315:
                                        return VISTAAR_WEB_ONBOARDING_WHOIS_CONSENT_DIALOG;
                                    case 316:
                                        return GOOGLE_ASSISTANT_ACTION_LINK_CONFIRMATION;
                                    case 317:
                                        return YOUTUBE_WEB_WHAT_TO_WATCH_FEED;
                                    case 318:
                                        return NEST_AUTH_ANDROID_MERGE_FLOW;
                                    case 319:
                                        return NEST_AUTH_IOS_MERGE_FLOW;
                                    case 320:
                                        return NEST_AUTH_WEB_MERGE_FLOW;
                                    case 321:
                                        return DUO_ANDROID_DOWNGRADE_FROM_SETTINGS;
                                    case 322:
                                        return DUO_IOS_DOWNGRADE_FROM_SETTINGS;
                                    case 323:
                                        return GOOGLE_PAY_ANDROID_IMPORT_GMAIL_CONSENT_UI;
                                    case 324:
                                        return DUO_WEB_NEW_USER_SETUP_FLOW;
                                    case 325:
                                        return UDC_CONSENT_FLOWS_ANDROID;
                                    case 326:
                                        return UDC_CONSENT_FLOWS_IOS;
                                    case 327:
                                        return GOOGLE_ASSISTANT_KAIOS_CONSENT_UI;
                                    case 328:
                                        return MOBILE_DATA_PLAN_ANDROID_CONSENT_CHANGE;
                                    case 329:
                                        return YOUTUBE_GAMING_ANDROID_ACCOUNT_LINK_SETTINGS;
                                    case 330:
                                        return YOUTUBE_GAMING_IOS_ACCOUNT_LINK_SETTINGS;
                                    case 331:
                                        return YOUTUBE_GAMING_WEB_ACCOUNT_LINK_SETTINGS;
                                    case 332:
                                        return PHOTOS_ANDROID_FACE_CLUSTERING_EXPLICIT_PERMISSION_FLOW;
                                    case 333:
                                        return PHOTOS_ANDROID_FACE_CLUSTERING_ONBOARDING_DISCLAIMER_FLOW;
                                    case 334:
                                        return PHOTOS_ANDROID_FACE_CLUSTERING_SETTINGS_FLOW;
                                    case 335:
                                        return PHOTOS_ANDROID_FACE_CLUSTERING_STANDALONE_DISCLAIMER_FLOW;
                                    case 336:
                                        return PHOTOS_IOS_FACE_CLUSTERING_EXPLICIT_PERMISSION_FLOW;
                                    case 337:
                                        return PHOTOS_IOS_FACE_CLUSTERING_ONBOARDING_DISCLAIMER_FLOW;
                                    case 338:
                                        return PHOTOS_IOS_FACE_CLUSTERING_SETTINGS_FLOW;
                                    case 339:
                                        return PHOTOS_IOS_FACE_CLUSTERING_STANDALONE_DISCLAIMER_FLOW;
                                    case 340:
                                        return PHOTOS_WEB_FACE_CLUSTERING_EXPLICIT_PERMISSION_FLOW;
                                    case 341:
                                        return PHOTOS_WEB_FACE_CLUSTERING_ONBOARDING_DISCLAIMER_FLOW;
                                    case 342:
                                        return PHOTOS_WEB_FACE_CLUSTERING_SETTINGS_FLOW;
                                    case 343:
                                        return PHOTOS_WEB_FACE_CLUSTERING_STANDALONE_DISCLAIMER_FLOW;
                                    case 344:
                                        return ADS_SETTINGS_CONSENT_BUMP_1_WEB;
                                    case 345:
                                        return ADS_SETTINGS_WEB;
                                    case 346:
                                        return CRUISER_ANDROID_CONSENT_UI;
                                    case 347:
                                        return PLAY_GAMES_SERVICES_ANDROID_ENABLE_AUTO_SIGN_IN_FROM_GAME;
                                    case 348:
                                        return FITNESS_ANDROID_HISTORY_UI;
                                    case 349:
                                        return FITNESS_ANDROID_HOME_UI;
                                    case 350:
                                        return PHOTOS_IOS_AUTOBACKUP_SETTINGS_UPSELL_FLOW;
                                    case 351:
                                        return ASTERISM_ANDROID_SETUP_INVOKED;
                                    case 352:
                                        return ASTERISM_ANDROID_USER_INVOKED;
                                    case 353:
                                        return ASTERISM_ANDROID_FUNCTION_INVOKED;
                                    case 354:
                                        return GCP_MARKETPLACE_PRODUCT_PURCHASE;
                                    case 355:
                                        return CLOUD_AGREEMENT_CONTEXT;
                                    case 356:
                                        return YOUTUBE_GAMING_MWEB_ACCOUNT_LINK_WATCH;
                                    case 357:
                                        return GOOGLE_ONE_WEB_SPONSORED_MEMBERSHIP_ONBOARDING_FLOW;
                                    case 358:
                                        return FITNESS_ANDROID_WEAR_HOME_UI;
                                    case 359:
                                        return FITNESS_ANDROID_WEAR_SETTINGS_UI;
                                    case 360:
                                        return PLAY_CONSOLE_WEB_ADHOC_SHARING_UPLOAD;
                                    case 361:
                                        return GOOGLE_ONE_ANDROID_BACKUP_SETTINGS;
                                    case 362:
                                        return GOOGLE_ONE_ANDROID_ENABLE_BACKUP_HOME_TAB;
                                    case 363:
                                        return GOOGLE_ONE_ANDROID_SETUP_BACKUP;
                                    case 364:
                                        return YOUTUBE_GAMING_MWEB_ACCOUNT_LINK_SETTINGS;
                                    case 365:
                                        return ACTIVITY_CONTROLS_WEB;
                                    case 366:
                                        return ACTIVITY_CONTROLS_WEBVIEW;
                                    case 367:
                                        return GOOGLE_JACQUARD_ANDROID_ASSIGN_ABILITY_FLOW;
                                    case 368:
                                        return GOOGLE_JACQUARD_ANDROID_ONBOARDING_FLOW;
                                    case 369:
                                        return GOOGLE_JACQUARD_ANDROID_SETTING_FLOW;
                                    case 370:
                                        return GOOGLE_JACQUARD_IOS_ASSIGN_ABILITY_FLOW;
                                    case 371:
                                        return GOOGLE_JACQUARD_IOS_ONBOARDING_FLOW;
                                    case 372:
                                        return GOOGLE_JACQUARD_IOS_SETTING_FLOW;
                                    case 373:
                                        return GOOGLE_HOME_ANDROID_NEW_MANAGER_OOBE_FLOW_NEST;
                                    case 374:
                                        return GOOGLE_HOME_IOS_NEW_MANAGER_OOBE_FLOW_NEST;
                                    case 375:
                                        return GOOGLE_HOME_WEB_FRONTEND_NEW_MANAGER_OOBE_FLOW_NEST;
                                    case 376:
                                        return MOBILE_CONSENT_FLOWS_ANDROID_PLAY_MUSIC_ON_APP_START;
                                    case 377:
                                        return MOBILE_CONSENT_FLOWS_ANDROID_PLAY_MUSIC_ON_SETTINGS;
                                    case 378:
                                        return MOBILE_CONSENT_FLOWS_ANDROID_GPAY_APP_NOTIFICATION_SETTINGS;
                                    case 379:
                                        return ADH_CONSENT_WEB;
                                    case 380:
                                        return GOOGLE_ASSISTANT_ANDROID_FACE_MATCH_ENROLLMENT_CONSENT;
                                    case 381:
                                        return GOOGLE_ASSISTANT_ANDROID_PERSONAL_RESULTS_WITH_FACE_MATCH;
                                    case 382:
                                        return GOOGLE_ASSISTANT_ANDROID_UNICORN_FACE_MATCH_ENROLLMENT_CONSENT;
                                    case 383:
                                        return GOOGLE_ASSISTANT_ANDROID_UNICORN_PERSONAL_RESULTS_WITH_FACE_MATCH;
                                    case 384:
                                        return GOOGLE_ASSISTANT_IOS_FACE_MATCH_ENROLLMENT_CONSENT;
                                    case 385:
                                        return GOOGLE_ASSISTANT_IOS_PERSONAL_RESULTS_WITH_FACE_MATCH;
                                    case 386:
                                        return GOOGLE_ASSISTANT_IOS_UNICORN_FACE_MATCH_ENROLLMENT_CONSENT;
                                    case 387:
                                        return GOOGLE_ASSISTANT_IOS_UNICORN_PERSONAL_RESULTS_WITH_FACE_MATCH;
                                    case 388:
                                        return DOMAIN_REGISTRAR_RESELLER_API_WHOIS_CONSENT_FLOW;
                                    case 389:
                                        return YOUTUBE_WEB_TOS_WATCH;
                                    case 390:
                                        return YOUTUBE_MOBILE_WEB_TOS_WATCH;
                                    case 391:
                                        return YOUTUBE_ANDROID_TOS_WATCH;
                                    case 392:
                                        return YOUTUBE_IOS_TOS_WATCH;
                                    default:
                                        switch (i) {
                                            case 394:
                                                return YOUTUBE_WEB_TOS_BROWSE;
                                            case 395:
                                                return YOUTUBE_MOBILE_WEB_TOS_BROWSE;
                                            case 396:
                                                return YOUTUBE_ANDROID_TOS_BROWSE;
                                            case 397:
                                                return YOUTUBE_IOS_TOS_BROWSE;
                                            case 398:
                                                return CROWDSOURCE_ANDROID_GAZELLE_CONSENT_SCREEN;
                                            case ErrorInfo.TYPE_FSC_OTHER_ERROR:
                                                return GOOGLE_HOME_ANDROID_NEST_LINKING_FLOW;
                                            case 400:
                                                return GOOGLE_HOME_IOS_NEST_LINKING_FLOW;
                                            case ErrorInfo.TYPE_FELICA_EXCEPTION_FELICA_NOT_AVAILABLE:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_PHOTOS_ASSISTANT_CARD;
                                            case ErrorInfo.TYPE_FELICA_EXCEPTION_TIMEOUT_OCCURRED:
                                                return PAISA_MICROAPPS_PRIMER;
                                            case 403:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_SAFETYHUB_SHARING_ONBOARDING;
                                            case 404:
                                                return CROWDSOURCE_WEB_LEADERBOARDS_CONSENT_SCREEN;
                                            case 405:
                                                return CROWDSOURCE_WEB_SETTINGS_UI;
                                            case 406:
                                                return YOUTUBE_MUSIC_WEB_PREF_VALUE_MIGRATION;
                                            case 407:
                                                return WHITE_PAGES_SERVICE_ASSISTANT_COLLECT_PHONE_OUTBOUND_CALLS;
                                            case 408:
                                                return WHITE_PAGES_SERVICE_ASSISTANT_COLLECT_REACHABLE_PHONE;
                                            case 409:
                                                return WHITE_PAGES_SERVICE_COMMON_BROAD_CONSENT;
                                            case 410:
                                                return WHITE_PAGES_SERVICE_COMMON_DISCOVERABILITY_CONSENT;
                                            case 411:
                                                return WHITE_PAGES_SERVICE_COMMON_REACHABILITY_CONSENT;
                                            case 412:
                                                return WHITE_PAGES_SERVICE_GAIA_COLLECT_REACHABLE_PHONE_AFTER_RECOVERY;
                                            case 413:
                                                return WHITE_PAGES_SERVICE_GAIA_COLLECT_REACHABLE_PHONE_REGULAR_SIGN_IN;
                                            case 414:
                                                return ADS_SETTINGS_WEBVIEW;
                                            case 415:
                                                return ADS_SETTINGS_CONSENT_BUMP_1_WEBVIEW;
                                            case 416:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_CARD;
                                            case 417:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_ON_APP_START;
                                            case 418:
                                                return FITNESS_ANDROID_WEAR_ONBOARDING_FLOW;
                                            case 419:
                                                return FAMILYLINK_CHROME_OS_SUPERVISION_OPTIN_UI;
                                            case 420:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_YOUTUBE_MUSIC_HOME_LH_DIRECT_ASK;
                                            case 421:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_YOUTUBE_MUSIC_HOME_LH_PROMO;
                                            case 422:
                                                return PAISA_MICROAPPS_ANDROID_PERMISSION_CONSENT_DIALOG;
                                            case 423:
                                                return PAISA_MICROAPPS_IOS_PERMISSION_CONSENT_DIALOG;
                                            case 424:
                                                return MINUTEMAID_LIGHTWEIGHT_SIGN_UP;
                                            case 425:
                                                return GOOGLE_PAY_GMSCORE_PAY_IMPORT_GMAIL_CONSENT_UI;
                                            case 426:
                                                return CONTACTS_SYNC_ANDROID_BACKUP_SYNC_OPT_IN;
                                            case 427:
                                                return PAISA_DONATION_MICROAPP_WEB;
                                            case 428:
                                                return FLOURISH_ANDROID_CONTRIBUTE_FLOW;
                                            case 429:
                                                return FLOURISH_ANDROID_REVOKE_CONSENT_PROMPT;
                                            case 430:
                                                return CRUISER_WEB_PUBMATE_TOS_UI;
                                            case 431:
                                                return COLABORATORY_PROPAGATE_DRIVE_CREDS_CONSENT_UI;
                                            case 432:
                                                return CROWDSOURCE_ANDROID_MOBILE_RAID_CONSENT_SCREEN;
                                            case 433:
                                                return YOUTUBE_WEB_BRAND_ACCOUNT_CHANNEL_CREATION_V2;
                                            case 434:
                                                return GOOGLE_HOME_ANDROID_MIGRATION_FLOW;
                                            case 435:
                                                return GOOGLE_HOME_IOS_MIGRATION_FLOW;
                                            case 436:
                                                return PAISA_MICROAPPS_ANDROID_DISCLAIMER_REVOCATION_DIALOG;
                                            case 437:
                                                return PAISA_MICROAPPS_IOS_DISCLAIMER_REVOCATION_DIALOG;
                                            case 438:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_ON_CONSENT_CHECK;
                                            case 439:
                                                return RIDESHARING_GMM_ANDROID_TAXI_TAB_PER_PROVIDER_CONSENT_V1;
                                            case 440:
                                                return RIDESHARING_GMM_IOS_TAXI_TAB_PER_PROVIDER_CONSENT_V1;
                                            case 441:
                                                return CONTACTS_SYNC_ANDROID_CONTACTS_APP_PROMO;
                                            case 442:
                                                return UNICORN_EMAIL_OPT_IN_ANDROID_ALL_SET;
                                            case 443:
                                                return PAISA_MICROAPPS_FLUTTER_PERMISSION_CONSENT_DIALOG;
                                            case 444:
                                                return PRESTO_ANDROID_MAESTRO_OOBE_FLOW;
                                            case 445:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_MAPS_TIMELINE_ONBOARDING;
                                            case 446:
                                                return PLAY_GAMES_SERVICES_ANDROID_FRIENDS_AND_YOUR_PRIVACY_FLOW;
                                            case 447:
                                                return PLAY_GAMES_SERVICES_ANDROID_FRIENDS_LIST_VISIBILITY_IN_GAME_FLOW;
                                            case 448:
                                                return GOOGLE_PAY_IOS_GMAIL_IMPORT_CONSENT_UI;
                                            case 449:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_MAPS_HOME_SCREEN_CONTRIBUTE_TAB;
                                            case 450:
                                                return GOOGLE_HOME_WEB_FRONTEND_PROMOTION;
                                            case 451:
                                                return MADDEN_WEB_FINALIZE_PARKING_SESSION_FLOW;
                                            case 452:
                                                return GOOGLE_PAY_GMSCORE_PAY_SETTINGS;
                                            case 453:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_MAPS_PERSONAL_SCORE_SETUP;
                                            case 454:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_MAPS_ULR_OOB_TUTORIAL;
                                            case 455:
                                                return MOBILE_CONSENT_FLOWS_ANDROID_MAPS_YOUR_PLACES_VISITED;
                                            case 456:
                                                return CONSENT_CAMPAIGN_WEB_DASHER_TO_CONSUMER_CONVERSION_UI;
                                            case 457:
                                                return GOOGLE_PAY_MOBILE_WEB_SETTINGS;
                                            case 458:
                                                return GOOGLE_ONE_IOS_BACKUP_SETTINGS;
                                            case 459:
                                                return GOOGLE_ONE_IOS_ENABLE_BACKUP_HOME_TAB;
                                            case 460:
                                                return GOOGLE_ONE_IOS_FAMILY_SHARING_SETTING;
                                            case 461:
                                                return GOOGLE_ONE_IOS_FAMILY_SHARING_SETTING_HOME_TAB;
                                            case 462:
                                                return GOOGLE_ONE_IOS_MARKETING_SETTING;
                                            case 463:
                                                return GOOGLE_ONE_IOS_PURCHASE_FLOW;
                                            case 464:
                                                return GOOGLE_ONE_IOS_SETUP_BACKUP;
                                            case 465:
                                                return COLABORATORY_SUBSCRIPTION_BUY_FLOW_UI;
                                            case 466:
                                                return CROWDSOURCE_LEADERBOARDS_CONSENT_SCREEN;
                                            case 467:
                                                return CROWDSOURCE_SETTINGS_UI;
                                            case 468:
                                                return PLAY_GAMES_SERVICES_WEB_CREATE_PROFILE_FLOW;
                                            case 469:
                                                return PLAY_GAMES_SERVICES_WEB_EDIT_PROFILE_FLOW;
                                            case 470:
                                                return GOOGLE_HOME_ANDROID_E911_OOBE;
                                            case 471:
                                                return GOOGLE_HOME_ANDROID_E911_SETTINGS;
                                            case 472:
                                                return GOOGLE_HOME_ANDROID_FAMILIAR_FACE_DETECTION_OOBE;
                                            case 473:
                                                return GOOGLE_HOME_ANDROID_FAMILIAR_FACE_DETECTION_SETTINGS;
                                            case 474:
                                                return GOOGLE_HOME_ANDROID_SOUND_SENSING_OOBE;
                                            case 475:
                                                return GOOGLE_HOME_ANDROID_SOUND_SENSING_SETTINGS;
                                            case 476:
                                                return GOOGLE_HOME_IOS_E911_OOBE;
                                            case 477:
                                                return GOOGLE_HOME_IOS_E911_SETTINGS;
                                            case 478:
                                                return GOOGLE_HOME_IOS_FAMILIAR_FACE_DETECTION_OOBE;
                                            case 479:
                                                return GOOGLE_HOME_IOS_FAMILIAR_FACE_DETECTION_SETTINGS;
                                            case 480:
                                                return GOOGLE_HOME_IOS_SOUND_SENSING_OOBE;
                                            case 481:
                                                return GOOGLE_HOME_IOS_SOUND_SENSING_SETTINGS;
                                            case 482:
                                                return PLAY_GAMES_SERVICES_WEB_SETTINGS;
                                            case 483:
                                                return GOOGLE_HOME_ANDROID_HOME_TAB_ACTION_CHIPS;
                                            case 484:
                                                return GOOGLE_HOME_IOS_HOME_TAB_VIEW;
                                            case 485:
                                                return GOOGLE_MAPS_AUTOMOTIVE_ANDROID_NAV_SESSION_LOGGING_PERMISSION;
                                            case 486:
                                                return GOOGLE_MAPS_AUTOMOTIVE_ANDROID_OFFLINE_MAPS_DOWNLOAD_PERMISSION;
                                            case 487:
                                                return GOOGLE_MAPS_AUTOMOTIVE_ANDROID_PRIVACY_CENTER_HOME;
                                            case 488:
                                                return YOUTUBE_MUSIC_WEB_TOS_UPLOAD;
                                            case 489:
                                                return GOOGLE_PAY_GMSCORE_PAY_VALUABLE_SIGNUP_UI;
                                            case 490:
                                                return PHOTOS_ANDROID_GOOGLE_ONE_SWITCH_STORAGE_POLICY_FLOW;
                                            case 491:
                                                return CROWDSOURCE_ANDROID_SMART_CAMERA_OPENSOURCE_DIALOG;
                                            case 492:
                                                return PLAY_CONSOLE_WEB_ADHOC_SHARING_UPLOAD_BREWDOG;
                                            case 493:
                                                return GOOGLE_HOME_ANDROID_NEST_AWARE_TRIAL_OFFER;
                                            case 494:
                                                return GOOGLE_HOME_IOS_NEST_AWARE_TRIAL_OFFER;
                                            case 495:
                                                return NEST_ANDROID_NEST_AWARE_TRIAL_OFFER;
                                            case 496:
                                                return NEST_IOS_NEST_AWARE_TRIAL_OFFER;
                                            case 497:
                                                return FAMILYLINK_WEB_PARENTAL_CONSENT_CC_UI;
                                            case 498:
                                                return FAMILYLINK_WEB_PARENTAL_CONSENT_RAPT_UI;
                                            case ErrorInfo.TYPE_FELICA_EXCEPTION_OTHER:
                                                return NEST_WEB_NEST_AWARE_TRIAL_OFFER;
                                            case 500:
                                                return PAISA_MONEY_TAB_FLUTTER;
                                            case 501:
                                                return CRUISER_WEB_REDEMPTION_CONSENT_UI;
                                            case 502:
                                                return PLAY_CONSOLE_WEB_USER_CONSOLE_TOS;
                                            case 503:
                                                return PHOTOS_IOS_GOOGLE_ONE_SWITCH_STORAGE_POLICY_FLOW;
                                            case 504:
                                                return PAISA_USER_MERCHANT_CREDIT_BOOK_CONSENT_FLOW_ANDROID;
                                            case 505:
                                                return GBOARD_ANDROID_DONATE_VOICE_CONSENT;
                                            case 506:
                                                return GBOARD_ANDROID_DONATE_VOICE_OPT_OUT;
                                            case 507:
                                                return TRAVEL_REENGAGEMENT_WEB_SEARCH_RESULTS_PAGE_OD_TRACK_BUTTON;
                                            case 508:
                                                return TRAVEL_REENGAGEMENT_WEB_SEARCH_RESULTS_PAGE_OD_UNDO_TRACK_BUTTON;
                                            case 509:
                                                return GCP_MARKETPLACE_WEB_SOLUTION_TRIAL;
                                            case 510:
                                                return UNICORN_SECONDARY_EDU_ACCOUNT_EMBEDDED_COEXISTENCE_CHROME_OS;
                                            default:
                                                return null;
                                        }
                                }
                        }
                }
        }
    }

    /* renamed from: b */
    public static bxvr m115994b() {
        return bsmw.f145464a;
    }

    /* renamed from: a */
    public final int mo3214a() {
        return this.f145962iC;
    }

    public final String toString() {
        return Integer.toString(this.f145962iC);
    }
}
