package p000;

import com.felicanetworks.mfc.FelicaException;
import com.felicanetworks.mfc.KeyInformation;
import com.felicanetworks.mfc.mfi.BaseMfiEventCallback;
import com.felicanetworks.mfc.mfi.MfiClientException;
import com.felicanetworks.sdu.ErrorInfo;
import com.google.autofill.detection.p098ml.AndroidInputTypeSignal;

/* renamed from: bsmz */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum bsmz implements bxvp {
    EVENT_NAME_UNSPECIFIED(0),
    ACTIVITY_CONTROLS_SETTING_CHANGE(193),
    ADH_CONSENT_CHANGE(198),
    ADS_GAP_NAC_SETTINGS_CHANGE(141),
    ANDROID_AUTO_SETUP_WIZARD_GOOGLE_SERVICES_SCREEN_ACCEPTED(145),
    ANDROID_BACKUP_SETTING_CHANGE(17),
    ANDROID_BACKUP_SET_ACCOUNT(16),
    ANDROID_SETUP_WIZARD_PIXEL_TOS_ACCEPTED(79),
    ANDROID_TV_SETUP_WIZARD_GOOGLE_SERVICES_SCREEN_ACCEPTED(28),
    APPLIED_CS_WITH_ANDROID_USER_REGISTRATION(94),
    ARC_BACKUP_AND_RESTORE_SETTING_CHANGE(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_POSTAL_ADDRESS),
    ARC_GOOGLE_LOCATION_SERVICE_SETTING_CHANGE(113),
    ARC_PLAY_ENABLED_SETTING_CHANGE(130),
    ARC_PLAY_TERMS_OF_SERVICE_CONSENT_FLOW_COMPLETED(114),
    ASTERISM_CLIENT_CONSENT_CHANGE(187),
    BQ_DTS_3P_TOS_ACCEPTED(163),
    CFS_ACCEPT_CONSENT_FLOW_EVENT(6),
    CFS_FETCH_CONSENT_FLOW_EVENT(5),
    CHROME_CLOUDCAST_SOCIAL_CONSENT_CHANGE(166),
    CHROME_CLOUDCAST_TERMS_OF_SERVICE_CHANGE(171),
    CHROME_SYNC_CONSENT(51),
    CHROME_UNIFIED_CONSENT_FLOW_COMPLETED(140),
    CLOUD_AGREEMENT_EVENT(189),
    CLOUD_CONSOLE_PERSONALIZATION_SETTINGS_CHANGE(80),
    CLOUD_TALENT_SOLUTION_SHARE_DATA_CONSENT_CHANGE(131),
    COLABORATORY_PROPAGATE_DRIVE_CREDS_CONSENT_CHANGE(BaseMfiEventCallback.TYPE_AGREEMENT_NOT_ACCEPT),
    COLABORATORY_SUBSCRIPTION_TOS_CONSENT_ACCEPTED(227),
    CONSENT_CAMPAIGN_CONSENT_BUMP_1_ACCEPTED(134),
    CONSENT_CAMPAIGN_CONSENT_BUMP_2_DECIDED(123),
    CONSENT_CAMPAIGN_REGULAR_ACCOUNT_ACTIVATION_CAMPAIGNS_DECIDED(147),
    CONSTELLATION_CONSENT_CHANGE(3),
    CONSTELLATION_SETTINGS_DISPLAY(7),
    CONTACTS_SYNC_BACKUP_SYNC_SETTING_CHANGE(BaseMfiEventCallback.TYPE_CARD_NOT_UNIQUE),
    CROWDSOURCE_GAZELLE_CONSENT(203),
    CROWDSOURCE_IMAGE_CAPTURE_CONSENT(106),
    CROWDSOURCE_IMAGE_CAPTURE_OPENSOURCE_CONSENT(ErrorInfo.TYPE_SDU_MEMORY_FULL),
    CROWDSOURCE_LEADERBOARDS_CONSENT(205),
    CROWDSOURCE_MOBILE_RAID_CONSENT(BaseMfiEventCallback.TYPE_OPSRV_REQUIRED_LIB_UNAVAILABLE),
    CROWDSOURCE_SMART_CAMERA_OPENSOURCE_CONSENT(241),
    CRUISER_SPONSOR_TERMS_OF_SERVICE_CONSENT_FLOW_COMPLETED(BaseMfiEventCallback.TYPE_OPSRV_RESULT_ERROR),
    CRUISER_TERMS_OF_SERVICE_CONSENT_FLOW_COMPLETED(185),
    DASHER_TO_CONSUMER_CONVERSION_ACCEPTED(225),
    DOMAIN_REGISTRAR_WHOIS_PUBLICATION_CONSENT_CHANGE(98),
    DRIVE_ANDROID_ADD_PHOTOS_CONSENT(107),
    DRIVE_IOS_BACKUP(75),
    DRIVE_WEB_ADD_PHOTOS_CONSENT(172),
    DUO_CONNECT_GAIA_CHANGE(124),
    FAMILIES_CREATE_FAMILY(34),
    FAMILIES_INTEGRATOR_TERMS_CONSENT(35),
    FAMILIES_JOIN_FAMILY(77),
    FAMILIES_SHARE_FOP_RENDER(76),
    FAMILIES_SHARE_PROFILE_CONSENT(36),
    FAMILIES_SHARE_PROFILE_RENDER(37),
    FAMILYLINK_ACCEPT_SUPERVISION_NOMINATION_ACCEPT_NOMINATION(MfiClientException.TYPE_CARD_NOT_CACHED),
    FAMILYLINK_ACCEPT_SUPERVISION_NOMINATION_FAMILY_CREATION(MfiClientException.TYPE_ILLEGAL_LINKAGE_DATA),
    FAMILYLINK_ACCEPT_SUPERVISION_NOMINATION_PRIVACY_NOTICE(MfiClientException.TYPE_NO_ACCOUNT_INFO),
    FAMILYLINK_JOIN_FAMILY_AND_ENABLE_SUPERVISION(BaseMfiEventCallback.TYPE_EXIST_UNKNOWN_CARD),
    FAMILYLINK_LOCATION_CONSENT(ErrorInfo.TYPE_SDU_COMMUNICATIONERROR),
    FAMILYLINK_PERSONAL_RESULTS_CONSENT(96),
    FAMILYLINK_SUPERVISION_CHANGE(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD),
    FAMILYLINK_SUPERVISION_NOMINATION_JOIN_FAMILY(MfiClientException.TYPE_MFICLIENT_NOT_ACTIVATED),
    FAMILYLINK_SUPERVISION_NOMINATION_NOMINATE_PARENT(MfiClientException.TYPE_MFICLIENT_STARTED),
    FAMILYLINK_SUPERVISION_NOMINATION_OPT_IN_SUPERVISION(MfiClientException.TYPE_MFICLIENT_NOT_STARTED),
    FAMILYLINK_SUPERVISION_PARENTAL_CONSENT_CC(246),
    FAMILYLINK_SUPERVISION_PARENTAL_CONSENT_RAPT(247),
    FITNESS_ACTIVITY_RECOGNITION_CONSENT(129),
    FITNESS_ACTIVITY_RECOGNITION_PERMISSION_CONSENT(BaseMfiEventCallback.TYPE_ILLEGAL_LINKAGE_DATA),
    FITNESS_APPLE_HEALTHKIT_CONSENT(168),
    FITNESS_APPLE_HEALTHKIT_LOCATION_CONSENT(202),
    FITNESS_BACKGROUND_LOCATION_CONSENT(182),
    FITNESS_DIAGNOSTICS_CONSENT(169),
    FITNESS_LOCATION_BACKGROUND_PERMISSION_CONSENT(BaseMfiEventCallback.TYPE_INVALID_LINKAGE_DATA),
    FITNESS_SLEEP_RECOGNITION_CONSENT(186),
    FITNESS_WEAR_BODY_SENSOR_PERMISSION_CONSENT(BaseMfiEventCallback.TYPE_CARD_NOT_ACTIVE),
    FITNESS_WEAR_CONTINUOUS_HEART_RATE_MONITORING_CONSENT(190),
    FLOURISH_FLU_VACCINATION_PROMPTING_STUDY_CONSENT_CHANGE(BaseMfiEventCallback.TYPE_OPSRV_ACCOUNT_ERROR),
    FREIGHTER_HELP_IMPROVE_PRODUCT(ErrorInfo.TYPE_SDU_FAILED),
    GAIA_ACCOUNT_CREATED(11),
    GAIA_CHANGE_PHONE(9),
    GAIA_CREATE_ACCOUNT(27),
    GAIA_MINUTEMAID_SIGN_IN_CONSENT(120),
    GBOARD_DONATE_VOICE_CONSENT_CHANGE(253),
    GBOARD_TYPING_HISTORY_SYNC_CONSENT(MfiClientException.TYPE_ILLEGAL_CARD_OPERATION),
    GCP_MARKETPLACE_LEAD_SHARING(170),
    GCP_MARKETPLACE_LIFECYCLE_EVENT_SHARING(188),
    GCP_MARKETPLACE_SOLUTION_TRIAL(254),
    GOOGLE_ACCOUNT_PHONE_CONSTELLATION_CONSENT(255),
    GOOGLE_ACCOUNT_PHONE_DISCOVERABILITY_CHANGE(137),
    GOOGLE_ACCOUNT_PHONE_NUMBER_MERGE(136),
    GOOGLE_ASSISTANT_ACTION_LINKS_CHECK_IN_FLIGHT_CONSENT(177),
    GOOGLE_ASSISTANT_DUO_CREATE_CONSENT_CHANGE(128),
    GOOGLE_ASSISTANT_FACE_MATCH_CONSENT(BaseMfiEventCallback.TYPE_UNKNOWN_ERROR),
    GOOGLE_ASSISTANT_ONBOARDING_FETCH(133),
    GOOGLE_ASSISTANT_ONBOARDING_IMPRESSION(33),
    GOOGLE_ASSISTANT_PERSONALIZED_RESULTS_CONSENT_CHANGE(63),
    GOOGLE_ASSISTANT_VOICE_MATCH_CONSENT(92),
    GOOGLE_CHROMEBOOK_EMAIL_NOTIFICATIONS_CONSENT_CHANGE(250),
    GOOGLE_HOME_APP_CRASH_UPLOAD_CONSENT_CHANGE(95),
    GOOGLE_HOME_ASSISTANT_DISCLOSURES(64),
    GOOGLE_HOME_DEVICE_ARBITRATION_CONSENT_CHANGE(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_WEB_PASSWORD),
    GOOGLE_HOME_DUO_CREATE_CONSENT_CHANGE(125),
    GOOGLE_HOME_DUO_ENABLE_CONSENT_CHANGE(126),
    GOOGLE_HOME_E911_TOGGLED(235),
    GOOGLE_HOME_EMAIL_NOTIFICATIONS_CONSENT_CHANGE(65),
    GOOGLE_HOME_FAMILIAR_FACE_DETECTION_TOGGLED(234),
    GOOGLE_HOME_MIGRATION_FLOW_CONSENT_CHANGE(220),
    GOOGLE_HOME_NEST_AWARE_TOS_ACCEPTED(242),
    GOOGLE_HOME_NEST_AWARE_TOS_IMPRESSION(243),
    GOOGLE_HOME_PERSONALIZED_RESULTS_CONSENT_CHANGE(66),
    GOOGLE_HOME_SOUND_SENSING_IMPRESSION(232),
    GOOGLE_HOME_SOUND_SENSING_TOGGLED(233),
    GOOGLE_HOME_STRUCTURE_INVITATION_SENT(142),
    GOOGLE_HOME_STRUCTURE_MANAGEMENT_CHANGE(143),
    GOOGLE_HOME_THIRD_PARTY_MEDIA_LINKING_ACCEPTED(67),
    GOOGLE_HOME_TOS_DISCLOSURE(68),
    GOOGLE_HOME_UMA_CONSENT_CHANGE(69),
    GOOGLE_HOME_UNLINK_ACCOUNT_FROM_DEVICE(221),
    GOOGLE_JACQUARD_EMAIL_UPDATES_CONSENT_CHANGE(ErrorInfo.TYPE_SDU_UNKNOWN),
    GOOGLE_JACQUARD_LOCATION_ACCESS_CONSENT_CHANGE(195),
    GOOGLE_JACQUARD_MUSIC_TRACK_CONSENT_CHANGE(196),
    GOOGLE_JACQUARD_NOTIFICATIONS_CONSENT_CHANGE(197),
    GOOGLE_LOCATION_SERVICES_STATE_CHANGE(40),
    GOOGLE_MAPS_AUTOMOTIVE_NAV_SESSION_LOGGING_CONSENT_CHANGED(236),
    GOOGLE_MAPS_AUTOMOTIVE_OFFLINE_MAPS_DOWNLOAD_CONSENT_CHANGED(237),
    GOOGLE_MAPS_AUTOMOTIVE_PRIVACY_CENTER_SHOWN(238),
    GOOGLE_ONE_FAMILY_SHARING_CHANGE(148),
    GOOGLE_ONE_MARKETING_SETTING_CHANGE(149),
    GOOGLE_ONE_MMS_BACKUP_SETTING_CHANGE(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PHONETIC),
    GOOGLE_ONE_ONBOARDING(MfiClientException.TYPE_MFICLIENT_REMOTE_ACCESS_FAILED),
    GOOGLE_PAY_CONSENT_CHANGE(18),
    GOOGLE_PAY_LADDER_PROMOTION_ELECTION_CHANGE(45),
    GOOGLE_PAY_PRIVACY_POLICY(19),
    GOOGLE_PAY_REFERREE_ELECTION_CHANGE(57),
    GOOGLE_PAY_REFERRER_ELECTION_CHANGE(58),
    GOOGLE_PAY_SETTING_CHANGE(20),
    GOOGLE_PAY_VALUABLE_SIGNUP_MERCHANT_SHARING_ACCEPTED(162),
    GOOGLE_PAY_VISA_CHECKOUT_LINK(60),
    GOOGLE_PIXELBOOK_EMAIL_NOTIFICATIONS_CONSENT_CHANGE(102),
    GOOGLE_PIXEL_PHONE_EMAIL_NOTIFICATIONS_CONSENT_CHANGE(99),
    GOOGLE_PIXEL_SLATE_EMAIL_NOTIFICATIONS_CONSENT_CHANGE(164),
    GOOGLE_SERVICES_SCREEN_ACCEPTED(12),
    GOOGLE_SHOPPING_TRANSACTION_ORDER_DISCLOSURE(165),
    GOOGLE_TOS_ACCEPTED(132),
    GOOGLE_WIFI_APP_UMA_CONSENT_CHANGE(70),
    GOOGLE_WIFI_CLOUD_SERVICES_CONSENT_CHANGE(71),
    GOOGLE_WIFI_EMAIL_NOTIFICATIONS_CONSENT_CHANGE(72),
    GOOGLE_WIFI_GROUP_UMA_CONSENT_CHANGE(73),
    GOOGLE_WIFI_TOS_DISCLOSURE(74),
    ITHACA_CONSENT_CHANGE(167),
    LHLR_MERGE_LH_DISABLED(41),
    LOCATION_HISTORY_SETTING_CHANGE(21),
    LOCATION_SHARING_FETCH_CONSENT_FLOW_EVENT(109),
    LOCATION_SHARING_TOS_ACCEPTED(25),
    MADDEN_TOS_ACCEPTED(43),
    MOBILE_DATA_PLAN_CONSENT_CHANGE(183),
    NEST_AUTH_PRIVACY_TERMS(179),
    NETAPP_CLOUD_VOLUMES_THIRD_PARTY_NOTICE_CONSENT(MfiClientException.TYPE_MFICLIENT_CURRENTLY_ONLINE),
    OFFLINE_RECEIPTS_AUTO_PROCESS_PHOTOS_IMPRESSION(121),
    OFFLINE_RECEIPTS_AUTO_PROCESS_PHOTOS_SETTING_CHANGED(122),
    OPA_PAYMENTS_TOS_ACCEPTANCE_STORED(93),
    PAISA_DONATION_MICROAPP_TERMS_OF_SERVICE_ACCEPTANCE(BaseMfiEventCallback.TYPE_INTERRUPTED_ERROR),
    PAISA_MERCHANT_CONSENT_DISCLOSURE(175),
    PAISA_MICROAPPS_PERMISSION_CHANGE(BaseMfiEventCallback.TYPE_ISSUE_LIMIT_EXCEEDED),
    PAISA_MICROAPPS_PRIMER_ACCEPTANCE(204),
    PAISA_MONEY_TAB_FLUTTER_PERMISSION_CHANGE(248),
    PAISA_USER_MERCHANT_CREDIT_BOOK_CONSENT_DISCLOSURE(251),
    PAISA_USER_NPCI_CONSENT_DISCLOSURE(244),
    PAISA_USER_PROMOTIONS_CONSENT_DISCLOSURE(245),
    PAYMENTS_LEGAL_DOCUMENT_CONSENT(44),
    PERIODIC_PERSONALIZATION_REMINDERS_SETTING_CHANGE(52),
    PHONE_TO_GAIA_UPDATE_PHONE(78),
    PHOTOS_AUTOBACKUP_CHANGE(26),
    PHOTOS_DOWNLOAD_CONTENT_CHANGE(22),
    PHOTOS_FACE_CLUSTERING_CHANGE(184),
    PHOTOS_G1_UPGRADE_CONSENT(194),
    PHOTOS_SHARED_LIBRARY_PROPOSAL(23),
    PHOTOS_SHARED_LIBRARY_SETTINGS_CHANGED(59),
    PHOTOS_SHARED_LIBRARY_WITHDRAWAL(24),
    PHOTOS_SHARED_LIBRARY_WITHDRAWAL_ACCEPTED_PARTNER_SHARE_WITH_ANOTHER_USER(49),
    PHOTOS_SHARED_LIBRARY_WITHDRAWAL_FACE_CLUSTERING_DISABLED_CONSENT(127),
    PHOTOS_SHARED_LIBRARY_WITHDRAWAL_NO_MORE_SHARED_CLUSTERS_AVAILABLE(47),
    PHOTOS_SHARED_LIBRARY_WITHDRAWAL_NO_MORE_VISIBLE_CLUSTERS_AVAILABLE(48),
    PHOTOS_SHARED_LIBRARY_WITHDRAWAL_PROPOSED_PARTNER_SHARE_TO_ANOTHER_USER(50),
    PHOTOS_SHARED_LIBRARY_WITHDRAWAL_USER_BLOCKED(46),
    PLAY_CONSOLE_ADHOC_SHARING_UPLOAD_TOS_ACCEPTED(191),
    PLAY_CONSOLE_APP_SIGNING_TOS_ACCEPTED(135),
    PLAY_CONSOLE_PREFERENCES_CHANGE(15),
    PLAY_CONSOLE_PREFERENCES_DISPLAY(13),
    PLAY_CONSOLE_USER_CONSOLE_TOS_ACCEPTED(249),
    PLAY_GAMES_SERVICES_CONSENT_CHANGED(30),
    PRESTO_LEGAL_ARBITRATION_CONSENT(223),
    RIDESHARING_SHARING_ORIGIN_DESTINATION_WITH_3P_CONSENT(119),
    SHARED_ENDORSEMENTS_SETTING_CHANGE(2),
    TEST_EVENT(1),
    TRAVEL_REENGAGEMENT_FLIGHT_PRICE_EMAILS_CONSENT_CHANGED(82),
    TRAVEL_REENGAGEMENT_FLIGHT_TRACKING_CHANGED(83),
    TRAVEL_REENGAGEMENT_FLIGHT_TRAVEL_TIPS_CHANGED(84),
    TRAVEL_REENGAGEMENT_HOTEL_MARKET_TRACKING_CHANGED(85),
    TRAVEL_REENGAGEMENT_HOTEL_MARKET_TRACKING_UPDATED(86),
    TRAVEL_REENGAGEMENT_HOTEL_MARKET_TRAVEL_TIPS_CHANGED(97),
    TRAVEL_REENGAGEMENT_HOTEL_PRICE_EMAILS_CONSENT_CHANGED(87),
    TRAVEL_REENGAGEMENT_MDP_TRACKING_CHANGED(88),
    TRAVEL_REENGAGEMENT_MDP_TRAVEL_TIPS_CHANGED(89),
    TRAVEL_REENGAGEMENT_TRAVEL_TIPS_EMAILS_CONSENT_CHANGED(90),
    TRAVEL_REENGAGEMENT_TRIP_SUGGESTIONS_EMAILS_CONSENT_CHANGED(91),
    UDC_CONSENT_FLOW_ACCEPTED(180),
    UDC_CONSENT_FLOW_FETCH(181),
    UNICORN_ACCOUNT_CREATION_DNP_RENDER(38),
    UNICORN_ACCOUNT_CREATION_PRE_SIGNIN_DNP_RENDER(239),
    UNICORN_ACCOUNT_CREATION_SMS_PARENTAL_CONSENT(61),
    UNICORN_ACCOUNT_CREATION_STORE_PARENTAL_CONSENT(39),
    UNICORN_ACCOUNT_CREATION_TRUSTED_ACCOUNT_CONSENT(AndroidInputTypeSignal.TYPE_TEXT_VARIATION_FILTER),
    UNICORN_EMAIL_OPT_IN_CHANGED(222),
    UNICORN_GRADUATION(8),
    UNICORN_SECONDARY_EDU_ACCOUNT_SIGN_IN_PARENTAL_CONSENT(110),
    UNICORN_SECONDARY_EDU_ACCOUNT_SIGN_OUT_PARENTAL_CONSENT(111),
    UNICORN_SIGN_IN_DISCLAIMER_ACCEPTED(115),
    UNICORN_SIGN_IN_DNP_ACCEPTED(42),
    UNICORN_SUPERVISION_STORE_PARENTAL_CONSENT(160),
    VISTAAR_DOMAIN_WHOIS_CONSENT_CHANGE(174),
    VISTAAR_TOS_AGREEMENT_CONSENT(252),
    WAZE_LICENSE_AGREEMENT(54),
    WAZE_PRIVILEGES_CHANGE(55),
    WAZE_SETTING_CHANGE(56),
    WEAR_COMPANION_ACCOUNT_SYNC(116),
    WEAR_COMPANION_CLOUD_SYNC_CONSENT(117),
    WEAR_COMPANION_DIAGNOSTICS_CONSENT(118),
    WHITE_PAGES_SERVICE_BROAD_USE_CONSENT(BaseMfiEventCallback.TYPE_SERVER_GENERAL_ERROR),
    WHITE_PAGES_SERVICE_REACHABILITY_OR_DISCOVERABILITY_CONSENT(BaseMfiEventCallback.TYPE_EXPIRED_MFI),
    WHITE_PAGES_SERVICE_VERIFICATION_CONSENT(208),
    WIFI_SCAN_SETTINGS_UPDATE_PRE_P_CONSENT(81),
    YOUNG_TEEN_ACCOUNT_CREATION_DNP_RENDER(31),
    YOUNG_TEEN_ACCOUNT_CREATION_SMS_PARENTAL_CONSENT(62),
    YOUTUBE_ACCOUNT_LINK_GAL_STATE_CHANGE(226),
    YOUTUBE_CHANNEL_CREATION(29),
    YOUTUBE_GAMING_ACCOUNT_LINK_CHANGED(146),
    YOUTUBE_MUSIC_LOCATION_BASED_RECOMMENDATIONS_CONSENT_CHANGE(53),
    YOUTUBE_MUSIC_TOS_ACCEPTANCE(240),
    YOUTUBE_SEARCH_HISTORY_CHANGED(100),
    YOUTUBE_SHARE_ENCRYPTED_USER_ID_WITH_SHEERID(MfiClientException.TYPE_MFICLIENT_NOT_FOUND),
    YOUTUBE_TOS_ACCEPTANCE(ErrorInfo.TYPE_ACTIVATE_FELICA_HTTP_ERROR),
    YOUTUBE_WATCH_HISTORY_CHANGED(101),
    GAIA_MINUTEMAID_ACCOUNT_CREATED(10),
    PHOTOS_FACE_CLUSTERING_OPT_IN(161),
    PHOTOS_FACE_CLUSTERING_OPT_OUT(173),
    PLAY_CONSOLE_USAGE_COLLECTION_ACCEPTED(14),
    PSB_DARK_LAUNCH_EVENT(4),
    YOUNG_TEEN_ACCOUNT_CREATION_STORE_PARENTAL_CONSENT(32);
    

    /* renamed from: dO */
    public final int f146213dO;

    private bsmz(int i) {
        this.f146213dO = i;
    }

    /* renamed from: a */
    public static bsmz m115997a(int i) {
        switch (i) {
            case 0:
                return EVENT_NAME_UNSPECIFIED;
            case 1:
                return TEST_EVENT;
            case 2:
                return SHARED_ENDORSEMENTS_SETTING_CHANGE;
            case 3:
                return CONSTELLATION_CONSENT_CHANGE;
            case 4:
                return PSB_DARK_LAUNCH_EVENT;
            case 5:
                return CFS_FETCH_CONSENT_FLOW_EVENT;
            case 6:
                return CFS_ACCEPT_CONSENT_FLOW_EVENT;
            case 7:
                return CONSTELLATION_SETTINGS_DISPLAY;
            case 8:
                return UNICORN_GRADUATION;
            case 9:
                return GAIA_CHANGE_PHONE;
            case 10:
                return GAIA_MINUTEMAID_ACCOUNT_CREATED;
            case 11:
                return GAIA_ACCOUNT_CREATED;
            case 12:
                return GOOGLE_SERVICES_SCREEN_ACCEPTED;
            case 13:
                return PLAY_CONSOLE_PREFERENCES_DISPLAY;
            case 14:
                return PLAY_CONSOLE_USAGE_COLLECTION_ACCEPTED;
            case 15:
                return PLAY_CONSOLE_PREFERENCES_CHANGE;
            case 16:
                return ANDROID_BACKUP_SET_ACCOUNT;
            case 17:
                return ANDROID_BACKUP_SETTING_CHANGE;
            case 18:
                return GOOGLE_PAY_CONSENT_CHANGE;
            case 19:
                return GOOGLE_PAY_PRIVACY_POLICY;
            case 20:
                return GOOGLE_PAY_SETTING_CHANGE;
            case 21:
                return LOCATION_HISTORY_SETTING_CHANGE;
            case 22:
                return PHOTOS_DOWNLOAD_CONTENT_CHANGE;
            case 23:
                return PHOTOS_SHARED_LIBRARY_PROPOSAL;
            case 24:
                return PHOTOS_SHARED_LIBRARY_WITHDRAWAL;
            case 25:
                return LOCATION_SHARING_TOS_ACCEPTED;
            case 26:
                return PHOTOS_AUTOBACKUP_CHANGE;
            case 27:
                return GAIA_CREATE_ACCOUNT;
            case 28:
                return ANDROID_TV_SETUP_WIZARD_GOOGLE_SERVICES_SCREEN_ACCEPTED;
            case 29:
                return YOUTUBE_CHANNEL_CREATION;
            case 30:
                return PLAY_GAMES_SERVICES_CONSENT_CHANGED;
            case 31:
                return YOUNG_TEEN_ACCOUNT_CREATION_DNP_RENDER;
            case 32:
                return YOUNG_TEEN_ACCOUNT_CREATION_STORE_PARENTAL_CONSENT;
            case 33:
                return GOOGLE_ASSISTANT_ONBOARDING_IMPRESSION;
            case 34:
                return FAMILIES_CREATE_FAMILY;
            case 35:
                return FAMILIES_INTEGRATOR_TERMS_CONSENT;
            case 36:
                return FAMILIES_SHARE_PROFILE_CONSENT;
            case FelicaException.TYPE_NOT_CLOSED:
                return FAMILIES_SHARE_PROFILE_RENDER;
            case FelicaException.TYPE_ILLEGAL_METHOD_CALL:
                return UNICORN_ACCOUNT_CREATION_DNP_RENDER;
            case FelicaException.TYPE_USED_BY_OTHER_APP:
                return UNICORN_ACCOUNT_CREATION_STORE_PARENTAL_CONSENT;
            case FelicaException.TYPE_PUSH_FAILED:
                return GOOGLE_LOCATION_SERVICES_STATE_CHANGE;
            case 41:
                return LHLR_MERGE_LH_DISABLED;
            case FelicaException.TYPE_ALREADY_ACTIVATED:
                return UNICORN_SIGN_IN_DNP_ACCEPTED;
            case FelicaException.TYPE_GET_BLOCK_COUNT_INFORMATION_FAILED:
                return MADDEN_TOS_ACCEPTED;
            case FelicaException.TYPE_RESET_FAILED:
                return PAYMENTS_LEGAL_DOCUMENT_CONSENT;
            case FelicaException.TYPE_GET_SYSTEM_CODE_LIST_FAILED:
                return GOOGLE_PAY_LADDER_PROMOTION_ELECTION_CHANGE;
            case FelicaException.TYPE_GET_CONTAINER_ID_FAILED:
                return PHOTOS_SHARED_LIBRARY_WITHDRAWAL_USER_BLOCKED;
            case 47:
                return PHOTOS_SHARED_LIBRARY_WITHDRAWAL_NO_MORE_SHARED_CLUSTERS_AVAILABLE;
            case 48:
                return PHOTOS_SHARED_LIBRARY_WITHDRAWAL_NO_MORE_VISIBLE_CLUSTERS_AVAILABLE;
            case FelicaException.TYPE_CURRENTLY_ACTIVATING:
                return PHOTOS_SHARED_LIBRARY_WITHDRAWAL_ACCEPTED_PARTNER_SHARE_WITH_ANOTHER_USER;
            case 50:
                return PHOTOS_SHARED_LIBRARY_WITHDRAWAL_PROPOSED_PARTNER_SHARE_TO_ANOTHER_USER;
            case 51:
                return CHROME_SYNC_CONSENT;
            case 52:
                return PERIODIC_PERSONALIZATION_REMINDERS_SETTING_CHANGE;
            case 53:
                return YOUTUBE_MUSIC_LOCATION_BASED_RECOMMENDATIONS_CONSENT_CHANGE;
            case 54:
                return WAZE_LICENSE_AGREEMENT;
            case 55:
                return WAZE_PRIVILEGES_CHANGE;
            case FelicaException.TYPE_ACTIVATE_FAILED:
                return WAZE_SETTING_CHANGE;
            case 57:
                return GOOGLE_PAY_REFERREE_ELECTION_CHANGE;
            case FelicaException.TYPE_OFFLINE_CANCELED:
                return GOOGLE_PAY_REFERRER_ELECTION_CHANGE;
            case FelicaException.TYPE_NOW_EXECUTING_FALP:
                return PHOTOS_SHARED_LIBRARY_SETTINGS_CHANGED;
            case FelicaException.TYPE_MFC_NOT_FOUND:
                return GOOGLE_PAY_VISA_CHECKOUT_LINK;
            case FelicaException.TYPE_INITIATE_ADHOC_ERROR:
                return UNICORN_ACCOUNT_CREATION_SMS_PARENTAL_CONSENT;
            case 62:
                return YOUNG_TEEN_ACCOUNT_CREATION_SMS_PARENTAL_CONSENT;
            case 63:
                return GOOGLE_ASSISTANT_PERSONALIZED_RESULTS_CONSENT_CHANGE;
            case 64:
                return GOOGLE_HOME_ASSISTANT_DISCLOSURES;
            case KeyInformation.AES128_DES56:
                return GOOGLE_HOME_EMAIL_NOTIFICATIONS_CONSENT_CHANGE;
            case 66:
                return GOOGLE_HOME_PERSONALIZED_RESULTS_CONSENT_CHANGE;
            case KeyInformation.AES128_DES112:
                return GOOGLE_HOME_THIRD_PARTY_MEDIA_LINKING_ACCEPTED;
            case 68:
                return GOOGLE_HOME_TOS_DISCLOSURE;
            case 69:
                return GOOGLE_HOME_UMA_CONSENT_CHANGE;
            case 70:
                return GOOGLE_WIFI_APP_UMA_CONSENT_CHANGE;
            case 71:
                return GOOGLE_WIFI_CLOUD_SERVICES_CONSENT_CHANGE;
            case 72:
                return GOOGLE_WIFI_EMAIL_NOTIFICATIONS_CONSENT_CHANGE;
            case 73:
                return GOOGLE_WIFI_GROUP_UMA_CONSENT_CHANGE;
            case 74:
                return GOOGLE_WIFI_TOS_DISCLOSURE;
            case 75:
                return DRIVE_IOS_BACKUP;
            case 76:
                return FAMILIES_SHARE_FOP_RENDER;
            case 77:
                return FAMILIES_JOIN_FAMILY;
            case 78:
                return PHONE_TO_GAIA_UPDATE_PHONE;
            case KeyInformation.AES128:
                return ANDROID_SETUP_WIZARD_PIXEL_TOS_ACCEPTED;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_LONG_MESSAGE /*80*/:
                return CLOUD_CONSOLE_PERSONALIZATION_SETTINGS_CHANGE;
            case 81:
                return WIFI_SCAN_SETTINGS_UPDATE_PRE_P_CONSENT;
            case 82:
                return TRAVEL_REENGAGEMENT_FLIGHT_PRICE_EMAILS_CONSENT_CHANGED;
            case 83:
                return TRAVEL_REENGAGEMENT_FLIGHT_TRACKING_CHANGED;
            case 84:
                return TRAVEL_REENGAGEMENT_FLIGHT_TRAVEL_TIPS_CHANGED;
            case 85:
                return TRAVEL_REENGAGEMENT_HOTEL_MARKET_TRACKING_CHANGED;
            case 86:
                return TRAVEL_REENGAGEMENT_HOTEL_MARKET_TRACKING_UPDATED;
            case 87:
                return TRAVEL_REENGAGEMENT_HOTEL_PRICE_EMAILS_CONSENT_CHANGED;
            case 88:
                return TRAVEL_REENGAGEMENT_MDP_TRACKING_CHANGED;
            case 89:
                return TRAVEL_REENGAGEMENT_MDP_TRAVEL_TIPS_CHANGED;
            case 90:
                return TRAVEL_REENGAGEMENT_TRAVEL_TIPS_EMAILS_CONSENT_CHANGED;
            case 91:
                return TRAVEL_REENGAGEMENT_TRIP_SUGGESTIONS_EMAILS_CONSENT_CHANGED;
            case 92:
                return GOOGLE_ASSISTANT_VOICE_MATCH_CONSENT;
            case 93:
                return OPA_PAYMENTS_TOS_ACCEPTANCE_STORED;
            case 94:
                return APPLIED_CS_WITH_ANDROID_USER_REGISTRATION;
            case 95:
                return GOOGLE_HOME_APP_CRASH_UPLOAD_CONSENT_CHANGE;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PERSON_NAME /*96*/:
                return FAMILYLINK_PERSONAL_RESULTS_CONSENT;
            case 97:
                return TRAVEL_REENGAGEMENT_HOTEL_MARKET_TRAVEL_TIPS_CHANGED;
            case 98:
                return DOMAIN_REGISTRAR_WHOIS_PUBLICATION_CONSENT_CHANGE;
            case 99:
                return GOOGLE_PIXEL_PHONE_EMAIL_NOTIFICATIONS_CONSENT_CHANGE;
            case 100:
                return YOUTUBE_SEARCH_HISTORY_CHANGED;
            case 101:
                return YOUTUBE_WATCH_HISTORY_CHANGED;
            case 102:
                return GOOGLE_PIXELBOOK_EMAIL_NOTIFICATIONS_CONSENT_CHANGE;
            case ErrorInfo.TYPE_SDU_COMMUNICATIONERROR:
                return FAMILYLINK_LOCATION_CONSENT;
            case ErrorInfo.TYPE_SDU_FAILED:
                return FREIGHTER_HELP_IMPROVE_PRODUCT;
            case ErrorInfo.TYPE_SDU_MEMORY_FULL:
                return CROWDSOURCE_IMAGE_CAPTURE_OPENSOURCE_CONSENT;
            case 106:
                return CROWDSOURCE_IMAGE_CAPTURE_CONSENT;
            case 107:
                return DRIVE_ANDROID_ADD_PHOTOS_CONSENT;
            case 108:
            case 138:
            case 139:
            case 178:
            case 228:
            case 229:
            case 230:
            case 231:
            default:
                return null;
            case 109:
                return LOCATION_SHARING_FETCH_CONSENT_FLOW_EVENT;
            case 110:
                return UNICORN_SECONDARY_EDU_ACCOUNT_SIGN_IN_PARENTAL_CONSENT;
            case 111:
                return UNICORN_SECONDARY_EDU_ACCOUNT_SIGN_OUT_PARENTAL_CONSENT;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_POSTAL_ADDRESS /*112*/:
                return ARC_BACKUP_AND_RESTORE_SETTING_CHANGE;
            case 113:
                return ARC_GOOGLE_LOCATION_SERVICE_SETTING_CHANGE;
            case 114:
                return ARC_PLAY_TERMS_OF_SERVICE_CONSENT_FLOW_COMPLETED;
            case 115:
                return UNICORN_SIGN_IN_DISCLAIMER_ACCEPTED;
            case 116:
                return WEAR_COMPANION_ACCOUNT_SYNC;
            case 117:
                return WEAR_COMPANION_CLOUD_SYNC_CONSENT;
            case 118:
                return WEAR_COMPANION_DIAGNOSTICS_CONSENT;
            case 119:
                return RIDESHARING_SHARING_ORIGIN_DESTINATION_WITH_3P_CONSENT;
            case 120:
                return GAIA_MINUTEMAID_SIGN_IN_CONSENT;
            case 121:
                return OFFLINE_RECEIPTS_AUTO_PROCESS_PHOTOS_IMPRESSION;
            case 122:
                return OFFLINE_RECEIPTS_AUTO_PROCESS_PHOTOS_SETTING_CHANGED;
            case 123:
                return CONSENT_CAMPAIGN_CONSENT_BUMP_2_DECIDED;
            case 124:
                return DUO_CONNECT_GAIA_CHANGE;
            case 125:
                return GOOGLE_HOME_DUO_CREATE_CONSENT_CHANGE;
            case 126:
                return GOOGLE_HOME_DUO_ENABLE_CONSENT_CHANGE;
            case 127:
                return PHOTOS_SHARED_LIBRARY_WITHDRAWAL_FACE_CLUSTERING_DISABLED_CONSENT;
            case 128:
                return GOOGLE_ASSISTANT_DUO_CREATE_CONSENT_CHANGE;
            case 129:
                return FITNESS_ACTIVITY_RECOGNITION_CONSENT;
            case 130:
                return ARC_PLAY_ENABLED_SETTING_CHANGE;
            case 131:
                return CLOUD_TALENT_SOLUTION_SHARE_DATA_CONSENT_CHANGE;
            case 132:
                return GOOGLE_TOS_ACCEPTED;
            case 133:
                return GOOGLE_ASSISTANT_ONBOARDING_FETCH;
            case 134:
                return CONSENT_CAMPAIGN_CONSENT_BUMP_1_ACCEPTED;
            case 135:
                return PLAY_CONSOLE_APP_SIGNING_TOS_ACCEPTED;
            case 136:
                return GOOGLE_ACCOUNT_PHONE_NUMBER_MERGE;
            case 137:
                return GOOGLE_ACCOUNT_PHONE_DISCOVERABILITY_CHANGE;
            case 140:
                return CHROME_UNIFIED_CONSENT_FLOW_COMPLETED;
            case 141:
                return ADS_GAP_NAC_SETTINGS_CHANGE;
            case 142:
                return GOOGLE_HOME_STRUCTURE_INVITATION_SENT;
            case 143:
                return GOOGLE_HOME_STRUCTURE_MANAGEMENT_CHANGE;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD /*144*/:
                return FAMILYLINK_SUPERVISION_CHANGE;
            case 145:
                return ANDROID_AUTO_SETUP_WIZARD_GOOGLE_SERVICES_SCREEN_ACCEPTED;
            case 146:
                return YOUTUBE_GAMING_ACCOUNT_LINK_CHANGED;
            case 147:
                return CONSENT_CAMPAIGN_REGULAR_ACCOUNT_ACTIVATION_CAMPAIGNS_DECIDED;
            case 148:
                return GOOGLE_ONE_FAMILY_SHARING_CHANGE;
            case 149:
                return GOOGLE_ONE_MARKETING_SETTING_CHANGE;
            case MfiClientException.TYPE_MFICLIENT_REMOTE_ACCESS_FAILED:
                return GOOGLE_ONE_ONBOARDING;
            case MfiClientException.TYPE_MFICLIENT_NOT_FOUND:
                return YOUTUBE_SHARE_ENCRYPTED_USER_ID_WITH_SHEERID;
            case MfiClientException.TYPE_MFICLIENT_NOT_ACTIVATED:
                return FAMILYLINK_SUPERVISION_NOMINATION_JOIN_FAMILY;
            case MfiClientException.TYPE_MFICLIENT_STARTED:
                return FAMILYLINK_SUPERVISION_NOMINATION_NOMINATE_PARENT;
            case MfiClientException.TYPE_MFICLIENT_NOT_STARTED:
                return FAMILYLINK_SUPERVISION_NOMINATION_OPT_IN_SUPERVISION;
            case MfiClientException.TYPE_ILLEGAL_LINKAGE_DATA:
                return FAMILYLINK_ACCEPT_SUPERVISION_NOMINATION_FAMILY_CREATION;
            case MfiClientException.TYPE_NO_ACCOUNT_INFO:
                return FAMILYLINK_ACCEPT_SUPERVISION_NOMINATION_PRIVACY_NOTICE;
            case MfiClientException.TYPE_CARD_NOT_CACHED:
                return FAMILYLINK_ACCEPT_SUPERVISION_NOMINATION_ACCEPT_NOMINATION;
            case MfiClientException.TYPE_ILLEGAL_CARD_OPERATION:
                return GBOARD_TYPING_HISTORY_SYNC_CONSENT;
            case MfiClientException.TYPE_MFICLIENT_CURRENTLY_ONLINE:
                return NETAPP_CLOUD_VOLUMES_THIRD_PARTY_NOTICE_CONSENT;
            case 160:
                return UNICORN_SUPERVISION_STORE_PARENTAL_CONSENT;
            case 161:
                return PHOTOS_FACE_CLUSTERING_OPT_IN;
            case 162:
                return GOOGLE_PAY_VALUABLE_SIGNUP_MERCHANT_SHARING_ACCEPTED;
            case 163:
                return BQ_DTS_3P_TOS_ACCEPTED;
            case 164:
                return GOOGLE_PIXEL_SLATE_EMAIL_NOTIFICATIONS_CONSENT_CHANGE;
            case 165:
                return GOOGLE_SHOPPING_TRANSACTION_ORDER_DISCLOSURE;
            case 166:
                return CHROME_CLOUDCAST_SOCIAL_CONSENT_CHANGE;
            case 167:
                return ITHACA_CONSENT_CHANGE;
            case 168:
                return FITNESS_APPLE_HEALTHKIT_CONSENT;
            case 169:
                return FITNESS_DIAGNOSTICS_CONSENT;
            case 170:
                return GCP_MARKETPLACE_LEAD_SHARING;
            case 171:
                return CHROME_CLOUDCAST_TERMS_OF_SERVICE_CHANGE;
            case 172:
                return DRIVE_WEB_ADD_PHOTOS_CONSENT;
            case 173:
                return PHOTOS_FACE_CLUSTERING_OPT_OUT;
            case 174:
                return VISTAAR_DOMAIN_WHOIS_CONSENT_CHANGE;
            case 175:
                return PAISA_MERCHANT_CONSENT_DISCLOSURE;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_FILTER /*176*/:
                return UNICORN_ACCOUNT_CREATION_TRUSTED_ACCOUNT_CONSENT;
            case 177:
                return GOOGLE_ASSISTANT_ACTION_LINKS_CHECK_IN_FLIGHT_CONSENT;
            case 179:
                return NEST_AUTH_PRIVACY_TERMS;
            case 180:
                return UDC_CONSENT_FLOW_ACCEPTED;
            case 181:
                return UDC_CONSENT_FLOW_FETCH;
            case 182:
                return FITNESS_BACKGROUND_LOCATION_CONSENT;
            case 183:
                return MOBILE_DATA_PLAN_CONSENT_CHANGE;
            case 184:
                return PHOTOS_FACE_CLUSTERING_CHANGE;
            case 185:
                return CRUISER_TERMS_OF_SERVICE_CONSENT_FLOW_COMPLETED;
            case 186:
                return FITNESS_SLEEP_RECOGNITION_CONSENT;
            case 187:
                return ASTERISM_CLIENT_CONSENT_CHANGE;
            case 188:
                return GCP_MARKETPLACE_LIFECYCLE_EVENT_SHARING;
            case 189:
                return CLOUD_AGREEMENT_EVENT;
            case 190:
                return FITNESS_WEAR_CONTINUOUS_HEART_RATE_MONITORING_CONSENT;
            case 191:
                return PLAY_CONSOLE_ADHOC_SHARING_UPLOAD_TOS_ACCEPTED;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PHONETIC /*192*/:
                return GOOGLE_ONE_MMS_BACKUP_SETTING_CHANGE;
            case 193:
                return ACTIVITY_CONTROLS_SETTING_CHANGE;
            case 194:
                return PHOTOS_G1_UPGRADE_CONSENT;
            case 195:
                return GOOGLE_JACQUARD_LOCATION_ACCESS_CONSENT_CHANGE;
            case 196:
                return GOOGLE_JACQUARD_MUSIC_TRACK_CONSENT_CHANGE;
            case 197:
                return GOOGLE_JACQUARD_NOTIFICATIONS_CONSENT_CHANGE;
            case 198:
                return ADH_CONSENT_CHANGE;
            case ErrorInfo.TYPE_SDU_UNKNOWN:
                return GOOGLE_JACQUARD_EMAIL_UPDATES_CONSENT_CHANGE;
            case BaseMfiEventCallback.TYPE_UNKNOWN_ERROR:
                return GOOGLE_ASSISTANT_FACE_MATCH_CONSENT;
            case ErrorInfo.TYPE_ACTIVATE_FELICA_HTTP_ERROR:
                return YOUTUBE_TOS_ACCEPTANCE;
            case 202:
                return FITNESS_APPLE_HEALTHKIT_LOCATION_CONSENT;
            case 203:
                return CROWDSOURCE_GAZELLE_CONSENT;
            case 204:
                return PAISA_MICROAPPS_PRIMER_ACCEPTANCE;
            case 205:
                return CROWDSOURCE_LEADERBOARDS_CONSENT;
            case BaseMfiEventCallback.TYPE_SERVER_GENERAL_ERROR:
                return WHITE_PAGES_SERVICE_BROAD_USE_CONSENT;
            case BaseMfiEventCallback.TYPE_EXPIRED_MFI:
                return WHITE_PAGES_SERVICE_REACHABILITY_OR_DISCOVERABILITY_CONSENT;
            case 208:
                return WHITE_PAGES_SERVICE_VERIFICATION_CONSENT;
            case BaseMfiEventCallback.TYPE_ILLEGAL_LINKAGE_DATA:
                return FITNESS_ACTIVITY_RECOGNITION_PERMISSION_CONSENT;
            case BaseMfiEventCallback.TYPE_INVALID_LINKAGE_DATA:
                return FITNESS_LOCATION_BACKGROUND_PERMISSION_CONSENT;
            case BaseMfiEventCallback.TYPE_CARD_NOT_ACTIVE:
                return FITNESS_WEAR_BODY_SENSOR_PERMISSION_CONSENT;
            case BaseMfiEventCallback.TYPE_EXIST_UNKNOWN_CARD:
                return FAMILYLINK_JOIN_FAMILY_AND_ENABLE_SUPERVISION;
            case BaseMfiEventCallback.TYPE_ISSUE_LIMIT_EXCEEDED:
                return PAISA_MICROAPPS_PERMISSION_CHANGE;
            case BaseMfiEventCallback.TYPE_CARD_NOT_UNIQUE:
                return CONTACTS_SYNC_BACKUP_SYNC_SETTING_CHANGE;
            case BaseMfiEventCallback.TYPE_INTERRUPTED_ERROR:
                return PAISA_DONATION_MICROAPP_TERMS_OF_SERVICE_ACCEPTANCE;
            case BaseMfiEventCallback.TYPE_OPSRV_ACCOUNT_ERROR:
                return FLOURISH_FLU_VACCINATION_PROMPTING_STUDY_CONSENT_CHANGE;
            case BaseMfiEventCallback.TYPE_OPSRV_RESULT_ERROR:
                return CRUISER_SPONSOR_TERMS_OF_SERVICE_CONSENT_FLOW_COMPLETED;
            case BaseMfiEventCallback.TYPE_AGREEMENT_NOT_ACCEPT:
                return COLABORATORY_PROPAGATE_DRIVE_CREDS_CONSENT_CHANGE;
            case BaseMfiEventCallback.TYPE_OPSRV_REQUIRED_LIB_UNAVAILABLE:
                return CROWDSOURCE_MOBILE_RAID_CONSENT;
            case 220:
                return GOOGLE_HOME_MIGRATION_FLOW_CONSENT_CHANGE;
            case 221:
                return GOOGLE_HOME_UNLINK_ACCOUNT_FROM_DEVICE;
            case 222:
                return UNICORN_EMAIL_OPT_IN_CHANGED;
            case 223:
                return PRESTO_LEGAL_ARBITRATION_CONSENT;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_WEB_PASSWORD /*224*/:
                return GOOGLE_HOME_DEVICE_ARBITRATION_CONSENT_CHANGE;
            case 225:
                return DASHER_TO_CONSUMER_CONVERSION_ACCEPTED;
            case 226:
                return YOUTUBE_ACCOUNT_LINK_GAL_STATE_CHANGE;
            case 227:
                return COLABORATORY_SUBSCRIPTION_TOS_CONSENT_ACCEPTED;
            case 232:
                return GOOGLE_HOME_SOUND_SENSING_IMPRESSION;
            case 233:
                return GOOGLE_HOME_SOUND_SENSING_TOGGLED;
            case 234:
                return GOOGLE_HOME_FAMILIAR_FACE_DETECTION_TOGGLED;
            case 235:
                return GOOGLE_HOME_E911_TOGGLED;
            case 236:
                return GOOGLE_MAPS_AUTOMOTIVE_NAV_SESSION_LOGGING_CONSENT_CHANGED;
            case 237:
                return GOOGLE_MAPS_AUTOMOTIVE_OFFLINE_MAPS_DOWNLOAD_CONSENT_CHANGED;
            case 238:
                return GOOGLE_MAPS_AUTOMOTIVE_PRIVACY_CENTER_SHOWN;
            case 239:
                return UNICORN_ACCOUNT_CREATION_PRE_SIGNIN_DNP_RENDER;
            case 240:
                return YOUTUBE_MUSIC_TOS_ACCEPTANCE;
            case 241:
                return CROWDSOURCE_SMART_CAMERA_OPENSOURCE_CONSENT;
            case 242:
                return GOOGLE_HOME_NEST_AWARE_TOS_ACCEPTED;
            case 243:
                return GOOGLE_HOME_NEST_AWARE_TOS_IMPRESSION;
            case 244:
                return PAISA_USER_NPCI_CONSENT_DISCLOSURE;
            case 245:
                return PAISA_USER_PROMOTIONS_CONSENT_DISCLOSURE;
            case 246:
                return FAMILYLINK_SUPERVISION_PARENTAL_CONSENT_CC;
            case 247:
                return FAMILYLINK_SUPERVISION_PARENTAL_CONSENT_RAPT;
            case 248:
                return PAISA_MONEY_TAB_FLUTTER_PERMISSION_CHANGE;
            case 249:
                return PLAY_CONSOLE_USER_CONSOLE_TOS_ACCEPTED;
            case 250:
                return GOOGLE_CHROMEBOOK_EMAIL_NOTIFICATIONS_CONSENT_CHANGE;
            case 251:
                return PAISA_USER_MERCHANT_CREDIT_BOOK_CONSENT_DISCLOSURE;
            case 252:
                return VISTAAR_TOS_AGREEMENT_CONSENT;
            case 253:
                return GBOARD_DONATE_VOICE_CONSENT_CHANGE;
            case 254:
                return GCP_MARKETPLACE_SOLUTION_TRIAL;
            case 255:
                return GOOGLE_ACCOUNT_PHONE_CONSTELLATION_CONSENT;
        }
    }

    /* renamed from: b */
    public static bxvr m115998b() {
        return bsmy.f145963a;
    }

    /* renamed from: a */
    public final int mo3214a() {
        return this.f146213dO;
    }

    public final String toString() {
        return Integer.toString(this.f146213dO);
    }
}
