package p000;

/* renamed from: bwx */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public final class bwx extends bwz {

    /* renamed from: a */
    public static final byte[] f5920a = {-97, 76};

    /* renamed from: b */
    public static final bzx f5921b = bzx.BOTH;

    /* renamed from: c */
    public static final bzu f5922c;

    /* renamed from: d */
    public static final int f5923d = 3;

    /* renamed from: e */
    public static final int f5924e = 1;

    /* renamed from: f */
    public static final int f5925f = 2;

    /* renamed from: g */
    public static final int f5926g = 5;

    /* renamed from: h */
    public static final int f5927h = 1;

    /* renamed from: i */
    public static final int f5928i = 1;

    static {
        bzv bzv = new bzv();
        bzv.f6286a = "ICC Dynamic Number";
        bzv.f6287b = "Time-variant number generated by the ICC, to be captured by the terminal";
        bzv.f6293h = f5923d;
        bzv.f6294i = f5924e;
        bzv.f6288c = f5920a;
        bzv.f6290e = f5921b;
        bzv.f6288c = f5920a;
        bzv.f6291f = 8;
        bzv.f6295j = f5925f;
        bzv.f6296k = f5926g;
        bzv.f6297l = f5928i;
        bzv.f6298m = f5927h;
        f5922c = bzv.mo3629a();
    }

    public bwx(byte[] bArr) {
        super(bArr, f5922c);
    }
}
