package p000;

import com.felicanetworks.mfc.FelicaException;
import com.felicanetworks.mfc.KeyInformation;
import com.felicanetworks.mfc.mfi.MfiClientException;
import com.felicanetworks.sdu.ErrorInfo;
import com.google.autofill.detection.p098ml.AndroidInputTypeSignal;

/* renamed from: bzqd */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public final class bzqd {
    /* renamed from: a */
    public static int m126036a(int i) {
        switch (i) {
            case 0:
                return 1;
            case 1:
                return 2;
            case 2:
                return 3;
            case 3:
                return 4;
            case 4:
                return 5;
            case 5:
                return 6;
            case 6:
                return 7;
            case 7:
                return 8;
            case 8:
                return 9;
            case 9:
                return 10;
            case 10:
                return 11;
            case 11:
                return 12;
            case 12:
                return 13;
            case 13:
                return 14;
            case 14:
                return 15;
            case 15:
                return 16;
            case 16:
                return 17;
            case 17:
                return 18;
            case 18:
                return 19;
            case 19:
                return 20;
            case 20:
                return 21;
            case 21:
                return 22;
            case 22:
                return 23;
            case 23:
                return 24;
            case 24:
                return 25;
            case 25:
                return 26;
            case 26:
                return 27;
            case 27:
                return 28;
            case 28:
                return 29;
            case 29:
                return 30;
            case 30:
                return 31;
            case 31:
                return 32;
            case 32:
                return 33;
            case 33:
                return 34;
            case 34:
                return 35;
            case 35:
                return 36;
            case 36:
                return 37;
            case FelicaException.TYPE_NOT_CLOSED:
                return 38;
            case FelicaException.TYPE_ILLEGAL_METHOD_CALL:
                return 39;
            case FelicaException.TYPE_USED_BY_OTHER_APP:
                return 40;
            case FelicaException.TYPE_PUSH_FAILED:
                return 41;
            case 41:
                return 42;
            case FelicaException.TYPE_ALREADY_ACTIVATED:
                return 43;
            case FelicaException.TYPE_GET_BLOCK_COUNT_INFORMATION_FAILED:
                return 44;
            case FelicaException.TYPE_RESET_FAILED:
                return 45;
            case FelicaException.TYPE_GET_SYSTEM_CODE_LIST_FAILED:
                return 46;
            case FelicaException.TYPE_GET_CONTAINER_ID_FAILED:
                return 47;
            case 47:
                return 48;
            case 48:
                return 49;
            case FelicaException.TYPE_CURRENTLY_ACTIVATING:
                return 50;
            case 50:
                return 51;
            case 51:
                return 52;
            case 52:
                return 53;
            case 53:
                return 54;
            case 54:
                return 55;
            case 55:
                return 56;
            case FelicaException.TYPE_ACTIVATE_FAILED:
                return 57;
            case 57:
                return 58;
            case FelicaException.TYPE_OFFLINE_CANCELED:
                return 59;
            case FelicaException.TYPE_NOW_EXECUTING_FALP:
                return 60;
            case FelicaException.TYPE_MFC_NOT_FOUND:
                return 61;
            case FelicaException.TYPE_INITIATE_ADHOC_ERROR:
                return 62;
            case 62:
                return 63;
            case 63:
                return 64;
            case 64:
                return 65;
            case KeyInformation.AES128_DES56:
                return 66;
            case 66:
                return 67;
            case KeyInformation.AES128_DES112:
                return 68;
            case 68:
                return 69;
            case 69:
                return 70;
            case 70:
                return 71;
            case 71:
                return 72;
            case 72:
                return 73;
            case 73:
                return 74;
            case 74:
                return 75;
            case 75:
                return 76;
            case 76:
                return 77;
            case 77:
                return 78;
            case 78:
                return 79;
            case KeyInformation.AES128:
                return 80;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_LONG_MESSAGE:
                return 81;
            case 81:
                return 82;
            case 82:
                return 83;
            case 83:
                return 84;
            case 84:
                return 85;
            case 85:
                return 86;
            case 86:
                return 87;
            case 87:
                return 88;
            case 88:
                return 89;
            case 89:
                return 90;
            case 90:
                return 91;
            case 91:
                return 92;
            case 92:
                return 93;
            case 93:
                return 94;
            case 94:
                return 95;
            case 95:
                return 96;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PERSON_NAME:
                return 97;
            case 97:
                return 98;
            case 98:
                return 99;
            case 99:
                return 100;
            case 100:
                return 101;
            case 101:
                return 102;
            case 102:
                return ErrorInfo.TYPE_SDU_COMMUNICATIONERROR;
            case ErrorInfo.TYPE_SDU_COMMUNICATIONERROR:
                return ErrorInfo.TYPE_SDU_FAILED;
            case ErrorInfo.TYPE_SDU_FAILED:
                return ErrorInfo.TYPE_SDU_MEMORY_FULL;
            case ErrorInfo.TYPE_SDU_MEMORY_FULL:
                return 106;
            case 106:
                return 107;
            case 107:
                return 108;
            case 108:
                return 109;
            case 109:
                return 110;
            case 110:
                return 111;
            case 111:
                return AndroidInputTypeSignal.TYPE_TEXT_VARIATION_POSTAL_ADDRESS;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_POSTAL_ADDRESS:
                return 113;
            case 113:
                return 114;
            case 114:
                return 115;
            case 115:
                return 116;
            case 116:
                return 117;
            case 117:
                return 118;
            case 118:
                return 119;
            case 119:
                return 120;
            case 120:
                return 121;
            case 121:
                return 122;
            case 122:
                return 123;
            case 123:
                return 124;
            case 124:
                return 125;
            case 125:
                return 126;
            case 126:
                return 127;
            case 127:
                return 128;
            case 128:
                return 129;
            case 129:
                return 130;
            case 130:
                return 131;
            case 131:
                return 132;
            case 132:
                return 133;
            case 133:
                return 134;
            case 134:
                return 135;
            case 135:
                return 136;
            case 136:
                return 137;
            case 137:
                return 138;
            case 138:
                return 139;
            case 139:
                return 140;
            case 140:
                return 141;
            case 141:
                return 142;
            case 142:
                return 143;
            case 143:
                return AndroidInputTypeSignal.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD:
                return 145;
            case 145:
                return 146;
            case 146:
                return 147;
            case 147:
                return 148;
            case 148:
                return 149;
            case 149:
                return MfiClientException.TYPE_MFICLIENT_REMOTE_ACCESS_FAILED;
            case MfiClientException.TYPE_MFICLIENT_REMOTE_ACCESS_FAILED:
                return MfiClientException.TYPE_MFICLIENT_NOT_FOUND;
            case MfiClientException.TYPE_MFICLIENT_NOT_FOUND:
                return MfiClientException.TYPE_MFICLIENT_NOT_ACTIVATED;
            case MfiClientException.TYPE_MFICLIENT_NOT_ACTIVATED:
                return MfiClientException.TYPE_MFICLIENT_STARTED;
            case MfiClientException.TYPE_MFICLIENT_STARTED:
                return MfiClientException.TYPE_MFICLIENT_NOT_STARTED;
            case MfiClientException.TYPE_MFICLIENT_NOT_STARTED:
                return MfiClientException.TYPE_ILLEGAL_LINKAGE_DATA;
            case MfiClientException.TYPE_ILLEGAL_LINKAGE_DATA:
                return MfiClientException.TYPE_NO_ACCOUNT_INFO;
            case MfiClientException.TYPE_NO_ACCOUNT_INFO:
                return MfiClientException.TYPE_CARD_NOT_CACHED;
            case MfiClientException.TYPE_CARD_NOT_CACHED:
                return MfiClientException.TYPE_ILLEGAL_CARD_OPERATION;
            case MfiClientException.TYPE_ILLEGAL_CARD_OPERATION:
                return MfiClientException.TYPE_MFICLIENT_CURRENTLY_ONLINE;
            case MfiClientException.TYPE_MFICLIENT_CURRENTLY_ONLINE:
                return 160;
            case 160:
                return 161;
            case 161:
                return 162;
            case 162:
                return 163;
            case 163:
                return 164;
            case 164:
                return 165;
            case 165:
                return 166;
            case 166:
                return 167;
            case 167:
                return 168;
            case 168:
                return 169;
            case 169:
                return 170;
            case 170:
                return 171;
            case 171:
                return 172;
            case 172:
                return 173;
            case 173:
                return 174;
            case 174:
                return 175;
            case 175:
                return AndroidInputTypeSignal.TYPE_TEXT_VARIATION_FILTER;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_FILTER:
                return 177;
            case 177:
                return 178;
            case 178:
                return 179;
            case 179:
                return 180;
            case 180:
                return 181;
            case 181:
                return 182;
            case 182:
                return 183;
            case 183:
                return 184;
            case 184:
                return 185;
            case 185:
                return 186;
            case 186:
                return 187;
            case 187:
                return 188;
            case 188:
                return 189;
            case 189:
                return 190;
            case 190:
                return 191;
            case 191:
                return AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PHONETIC;
            case AndroidInputTypeSignal.TYPE_TEXT_VARIATION_PHONETIC:
                return 193;
            case 193:
                return 194;
            default:
                return 0;
        }
    }
}
