package p000;

/* renamed from: cash */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum cash {
    CONTEXT_NOT_MATCHING,
    CREDENTIALS_NOT_ACCESSIBLE_WITHOUT_CVM,
    CREDENTIALS_NOT_AVAILABLE,
    INSUFFICIENT_CD_CVM,
    INSUFFICIENT_POI_AUTHENTICATION,
    MISSING_CARD_DATA,
    MISSING_CD_CVM,
    MISSING_CONSENT,
    MISSING_TERMINAL_DATA,
    POI_DECISION,
    POI_ENFORCED,
    TRANSACTION_CONDITIONS_NOT_ALLOWED,
    UNSUPPORTED_TRANSIT
}
