package p000;

/* renamed from: mcf */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum mcf {
    ELIGIBLE,
    INELIGIBLE_BLACKLISTED,
    INELIGIBLE_FULL_MIN_SDK,
    INELIGIBLE_KV_NO_AGENT,
    INELIGIBLE_KV_FULL_ONLY,
    INELIGIBLE_SIDEWINDER,
    INELIGIBLE_DOLLY_CONSENT,
    INELIGIBLE_PACKAGE_CONSENT,
    INELIGIBLE_FIRST_PARTY,
    INELIGIBLE_GCM,
    INELIGIBLE_UNSELECTED_CLOUD_RESTORE
}
