package p000;

/* renamed from: ntr */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum ntr {
    RESERVED_1,
    RESERVED_2,
    CAR_WINDOW_RESIZABLE,
    INT_SETTINGS_AVAILABLE,
    THIRD_PARTY_ACCESSIBLE_SETTINGS,
    CLIENT_SIDE_FLAGS,
    CONTENT_WINDOW_INSETS,
    ASSISTANT_Z,
    START_CAR_ACTIVITY_WITH_OPTIONS,
    STICKY_WINDOW_FOCUS,
    NON_CONTENT_WINDOW_ANIMATIONS_SAFE,
    WINDOW_REQUIRES_ONE_TEXTURE_UPDATE_TO_DRAW,
    CONNECTION_STATE_HISTORY,
    CLEAR_DATA,
    START_DUPLEX_CONNECTION,
    WINDOW_OUTSIDE_TOUCHES,
    CAR_WINDOW_REQUEST_FOCUS,
    SUPPORTS_SELF_MANAGED_CALLS,
    START_FIRST_CAR_ACTIVITY_ON_FOCUS_GAINED,
    MULTI_DISPLAY
}
