package p000;

/* renamed from: ofb */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum ofb {
    CHARGE_ONLY_DETECTED,
    CHARGE_ONLY_OVER,
    NO_ACCESSORY_MODE,
    FIRST_ACTIVITY_NOT_LAUNCHED,
    PROJECTION_NOT_STARTED,
    NO_ACCESSORY_MODE_FALSE_POSITIVE,
    FIRST_ACTIVITY_NOT_LAUNCHED_FALSE_POSITIVE,
    PROJECTION_NOT_STARTED_FALSE_POSITIVE,
    USB_RESET_SUPPRESSED
}
