package p000;

/* renamed from: ofc */
/* compiled from: :com.google.android.gms@201515033@20.15.15 (120300-306758586) */
public enum ofc {
    ENTERED_ACCESSORY_MODE,
    EXITED_ACCESSORY_MODE,
    CONFIGURED,
    LOST_CONFIGURED,
    CONNECTED,
    DISCONNECTED,
    ENTERED_MTP_MODE,
    EXITED_MTP_MODE,
    ENTERED_PTP_MODE,
    EXITED_PTP_MODE,
    DATA_UNLOCKED,
    DATA_LOCKED,
    ENTERED_ADB_MODE,
    EXITED_ADB_MODE,
    ENTERED_AUDIO_SOURCE_MODE,
    EXITED_AUDIO_SOURCE_MODE
}
